### ISSUE TITLE
Confusing text - 'Alread knows (those techs)' when in truth pawn is missing prerequisites

### ISSUE THREAD

**Issue by vlad1492** [jptrrs/HumanResources#10]
https://gist.github.com/a5393ff9c8d9a7a24f45cbfb8462d740

I bought a slave, he had high research skills. 
Tried to get him to research batteries, got the refusal that he already knew it. 
Made him study electricity, then he could study batteries. 

Just a misleading text.

**Comment by jptrrs** [comment]
Noted! Thanks.
