### ISSUE TITLE
Request for a hook

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#102]
Hello, I am the author of "Research Info" mod, and I was asked to make it compatible with your mod "Human Resources".
I've been trying to find a convenient way to get the value of a particular pawn's current research project and for now I can take this value from the "ResearchProjectDef project" field of JobDriver_LearnTech, but this approach has some limitations I would like to avoid..
So I would like to ask you to implement a hook, if possible, that would allow me or any other modder interested in doing this to get information about the current research project of a particular pawn in a more accessible and reliable way.
I see it something like that:

	public static ResearchProjectDef CurrentProjectOfPawn(Pawn pawn)
	{
		if (/*conditions, if necessary*/)
		{
			/*some internal logic*/
			return _researchProjectDef;
		}
		return null;
	}
	
So it returns research project that the pawn is currently researching.
Thanks for your attention!

**Comment by jptrrs** [comment]
Hi man! If only there were more modders willing to talk compatibility like that! Sure, let`s figure this out. 
I could implement some internal function to output that, but that would be going after exactly that field on the JobDriver. Actually, it lives on the parent class, JobDriver_Knowledge. I just checked it and realized I made it protected. Would it be easier for you if it was public? I'm curious, what are the limitations you're worried about?
You could do something like this:

```csharp
using HarmonyLib
{
	Type CurrentProjectType = AccessTools.TypeByName("HumanResources.JobDriver_Knowledge");
	FieldInfo CurrentProjectInfo = AccessTools.Field(CurrentProjectType, "project");

	public static ResearchProjectDef CurrentProjectOfPawn(Pawn pawn)
	{
		Job job = pawn.jobs.CurJob;
		if (CurrentProjectType.IsAssignableFrom(job.GetType()))
		{
			return (ResearchProjectDef)CurrentProjectInfo.GetValue(job);
		}
		return null;
	}
}
```

**Comment by Reiquard** [comment]
I tried it with the method you provided and it turns up that I can't get that value of the field without instantiating(?) (I've tried this many times to get the result via Harmony or directly System.Reflection - I can get the field itself, but can't get it's value)
So i ended up with this:

		public static Dictionary<Pawn, ResearchProjectDef> dictHR = new Dictionary<Pawn, ResearchProjectDef>();
		private static Type _JobDriver_LearnTech = AccessTools.TypeByName("HumanResources.JobDriver_LearnTech");
		private static FieldInfo _projectFI = AccessTools.Field(_JobDriver_LearnTech, "project");
		private static FieldInfo _pawnFI = AccessTools.Field(_JobDriver_LearnTech, "pawn");

		public static void Patcher() //executes via harmony initialization
		{
			ResearchInfo.Instance.Patch(AccessTools.Method(_JobDriver_LearnTech, "MakeNewToils"), null, new HarmonyMethod(AccessTools.Method(typeof(Utilities_HR), nameof(MakeNewToils_Postfix))));
		}

		private static void MakeNewToils_Postfix(object __instance)
		{
			Pawn pawn = (Pawn)_pawnFI.GetValue(__instance);
			ResearchProjectDef proj = (ResearchProjectDef)_projectFI.GetValue(__instance);
			if (dictHR.Count > 0)
			{
				if (dictHR.Keys.Contains(pawn))
				{
					Log.Message($"dictionary already contains this key");
					dictHR[pawn] = proj;
				}
				else
				{
					Log.Message($"adding to an existing dictionary");
					dictHR.Add(pawn, proj);
				}
			}
			else
			{
				Log.Message($"adding to an empty dictionary");
				dictHR.Add(pawn, proj);
			}
			var i = 0;
			foreach (KeyValuePair<Pawn, ResearchProjectDef> item in dictHR)
			{
				Log.Message($"-{++i} {item.Key}:[{item.Key.ThingID}]: {item.Value}");
			}
		}

		public static ResearchProjectDef HRGetProjectForPawn(Pawn pawn)
		{
			if (dictHR.Keys.Contains(pawn))
			{
				return dictHR[pawn];
			}
			return null;
		}

This code works, Debug log has the following lines after loading the save with three pawns performing research:

adding to an empty dictionary
-1 Зорро:[Human188]: Devilstrand
adding to an existing dictionary
-1 Зорро:[Human188]: Devilstrand
-2 Асрома:[Human194]: Brewing
adding to an existing dictionary
-1 Зорро:[Human188]: Devilstrand
-2 Асрома:[Human194]: Brewing
-3 Пурпурный:[Human196]: CarpetMaking

but after reloading the save (without reloading the game itself):

adding to an existing dictionary
-1 Зорро:[Human188]: Devilstrand
-2 Асрома:[Human194]: Brewing
-3 Пурпурный:[Human196]: CarpetMaking
-4 Зорро:[Human188]: Devilstrand
adding to an existing dictionary
-1 Зорро:[Human188]: Devilstrand
-2 Асрома:[Human194]: Brewing
-3 Пурпурный:[Human196]: CarpetMaking
-4 Зорро:[Human188]: Devilstrand
-5 Асрома:[Human194]: Brewing
adding to an existing dictionary
-1 Зорро:[Human188]: Devilstrand
-2 Асрома:[Human194]: Brewing
-3 Пурпурный:[Human196]: CarpetMaking
-4 Зорро:[Human188]: Devilstrand
-5 Асрома:[Human194]: Brewing
-6 Пурпурный:[Human196]: CarpetMaking

that is strange for me, since dictionary already contains those pawns as a keys:
	dictHR.Keys.Contains(pawn)
So I realized that I need to clear this dictionary every time I load the save, but I couldn't find where I can do this (Harmony seems to initialize after the first save load or even earlier) and as for this part of coding, that's where my knowledge ends.
I can try to use HughLib with ModBase, but I'm not sure that it's worth forcing many users to subscribe to additional content just for the sake of it.

As for the logic before executing this part of the code:

	if (pawn.CurJobDef == (JobDef)_ResearchTech.GetValue(_TechJobDefOf))//this field is static so I had no problems with it
	{
		if (pawn.Position == pawn.CurJob.targetA.Thing.InteractionCell)
		{
			project = HRGetProjectForPawn(Pawn pawn);
		}
	}
Sorry for the wall of text ;)

**Comment by jptrrs** [comment]
> I tried it with the method you provided and it turns up that I can't get that value of the field without instantiating(?) (I've tried this many times to get the result via Harmony or directly System.Reflection - I can get the field itself, but can't get it's value)

The jobs on RW are only instantiated when the workgivers give the pawns the go-ahead to perform that task. At that moment, the game runs the "TryMakePreToilReservations" for that particular job, and in our case that's when the "project" field is assigned, based on a number of conditions that vary depending on the particular pawn and task. (The researching and studying jobs are both handled by the JobDriver_LearnTech, but the criteria for selecting the project is different for each one. Not only that, but the player actions can also shift what project the pawns should pursue). That means each time a pawn starts one of the two jobs, a different project will be selected, and the flied value goes away as soon as the pawn interrupts the job. For this reason, I'm not sure keeping a dictionary is a good idea... And if you tried to get the value during the Harmony initialization that's why you couldn't.
With what I suggested, you wouldn't even need to patch anything. That code could run right where you would read your dictionary. You should have the Type and the Fieldinfo cached (for performance reasons), and the instance is the pawn's current job (pawn.jobs.CurJob). If at that time the pawn's not performing the right job, the function would return null, of course, so you gotta be prepared for that.

> that is strange for me, since dictionary already contains those pawns as a keys:
> dictHR.Keys.Contains(pawn)
> So I realized that I need to clear this dictionary every time I load the save, 

Actually, you would need to update the dictionary every time a pawn starts a research or study job. 

> but I couldn't find where I can do this (Harmony seems to initialize after the first save load or even earlier) and as for this part of coding, that's where my knowledge ends.

Harmony initializes right when the game starts, before everything. :-)

> I can try to use HughLib with ModBase, but I'm not sure that it's worth forcing many users to subscribe to additional content just for the sake of it.

If it's just for the sake of accessing a field value, sure there's no need for that!

If you uploaded your source to GitHub, I would gladly point out where to plug HR in...

**Comment by Reiquard** [comment]
Thanks for the explanation, it helped me achieve what was required, although it took quite some time to understand why the method you suggested didn't work

		Job job = pawn.jobs.curJob;
		if (CurrentProjectType.IsAssignableFrom(job.GetType())) //false

		JobDriver job = pawn.jobs.curDriver;
		if (CurrentProjectType.IsAssignableFrom(job.GetType())) //true

> I'm not sure keeping a dictionary is a good idea...

As for the dictionary, it was a necessary solution under the current conditions.

> Actually, you would need to update the dictionary every time a pawn starts a research or study job.

It was it.

Thank you again for your help, I believe that the hook for the research project is no longer required, however there is still a part with the progress of the research, I will look at this tomorrow after sleep and work, good luck and all the best to you! ;)

**Comment by jptrrs** [comment]
Cool! I guess I'm used to using curJob on these JobDrivers and ended up thinking it was the same thing... Glad you figured it out.
As for the progress, you will find that on a dictionary in the pawn's CompKnowledge: 
`pawn.TryGetComp<CompKnowledge>().expertise[theResearchProjectDefYouWantToKnow]`

**Comment by jptrrs** [comment]
Oh, BTW, I've introduced [this new key](https://github.com/jptrrs/HumanResources/blob/28b5141f821aadda4c2f51116ed0f2bc95566fad/Languages/Russian/Keyed/HumanResources_keys.xml#L22) that will require translation. It would be nice if you could check that off for russian!

**Comment by Reiquard** [comment]
After many failed attempts, I constructed this:

	private static Type _JobDriver_LearnTech = AccessTools.TypeByName("HumanResources.JobDriver_LearnTech");
	private static FieldInfo _projectFI = AccessTools.Field(_JobDriver_LearnTech, "project");
	private static Type _CompKnowledge = AccessTools.TypeByName("HumanResources.CompKnowledge");
	private static FieldInfo _expertiseFI = AccessTools.Field(_CompKnowledge, "expertise");

	public static (ResearchProjectDef, float) HRTuple_Project_Progress(Pawn pawn)
	{
		(ResearchProjectDef, float) tuple = (null, 0f);
		if (_JobDriver_LearnTech.IsAssignableFrom(pawn.jobs.curDriver.GetType()))
		{
			tuple.Item1 = (ResearchProjectDef)_projectFI.GetValue(pawn.jobs.curDriver);
		}
		for (int i = 0; i < pawn.AllComps.Count; i++)
		{
			if (_CompKnowledge.IsAssignableFrom(pawn.AllComps[i].GetType()))
			{
				tuple.Item2 = ((Dictionary<ResearchProjectDef, float>)_expertiseFI.GetValue(pawn.AllComps[i]))[tuple.Item1];
			}
		}
		return tuple;
	}

This construction works, but I have some doubts - whether it is correct to iterate pawn.AllComps at each request of this method (I haven't figured out how to solve this without iterating)

**Comment by jptrrs** [comment]
I can see why the iteration might be an issue.
You could also try reflecting the whole `pawn.TryGetComp<CompKnowledge>()`. It's a bit tricky to [patch generic methods](https://harmony.pardeike.net/articles/patching-edgecases.html#generics) but it's possible. Take a look [at this patch](https://github.com/jptrrs/HumanResources/blob/master/Source/Harmony/ThingOwnerUtility_GetAllThingsRecursively.cs), that uses `TargetMethod()` instead of annotating the patch and then `.MakeGenericMethod`.
