### ISSUE TITLE
New map generation zeroes free space

### ISSUE THREAD

**Issue by archielecroy** [jptrrs/HumanResources#108]
Upon generating a new map, the "Free space remaining in library" in my primary base gets set to 0. Saving and loading fixes the issue.

[Modlist](https://gist.github.com/archielecroy/cb03663a9a8a7921b8ecbba491321941)

**Comment by archielecroy** [comment]
#109 may fix this issue

**Comment by jptrrs** [comment]
Thanks for reporting this. Unfortunately I believe that PR won't solve the issue, it will take some more tinkering. I'm on it.

**Comment by jptrrs** [comment]
Solved for the next update, v0.29.
