### ISSUE TITLE
Incompatibility with TechBlock

### ISSUE THREAD

**Issue by MinerSebas** [jptrrs/HumanResources#11]
The Mod in Question:
https://steamcommunity.com/sharedfiles/filedetails/?id=1970774610

Actual Problem:
* The Understanding Techs this Mods adds, do not get a reduced Techcost for researching Techs of the same Level. (Regardless whether a Pawn has itself learned the other Techs or wrote them down)
  * The Research cost reduction should probably be by Pawn and not Global.
* Finishing an Understanding Tech doesn't give the Research progress in other Techs.
  * Even if it would work, it would create more Problems:
    * If the added Progress adds enough to finish a Tech, it circumvents the need to write a Book.
    * If the Progress isn't enough, then the added Progress is wasted.

Solution:
The mechanics of TechBlock goes against the Intent of this Mod.
Due to this, the Mod should be officially declared incompatible in the About.xml

**Comment by jptrrs** [comment]
Will do! Thanks for looking this up!
