### ISSUE TITLE
New settings style can lead to an error

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#111]
With the new settings style of knowledge generation it is now possible to uncheck all of four options that leads to
"[HumanResources] Couldn't calculate any expertise for PawnName" error upon pawn creation (tried via dev-mode).

**Comment by jptrrs** [comment]
I never imagined someone would try that, but you're right! I've written a validation routine to prevent this from happening. But with that, you've got yourself a new line to translate :-)
