### ISSUE TITLE
Repeatable error when wildman/refugee pod events happen

### ISSUE THREAD

**Issue by Afterthought-btw** [jptrrs/HumanResources#113]
Got an issue I assumed was just something to do with my install, but after verifying the integrity of the game files, deleting and reinstalling just the minimum mods I can still repeat it, so here we go.

Basically, whenever a wildman wanders in (or refugee pods land) I get these errors.

https://gist.github.com/HugsLibRecordKeeper/1cbe8db4bd3eafc10299e3e3d82ebd07

Should be easy to replicate - I just started a new game with Harmony, HugsLib, Research Pal, and this mod, and then used dev mode to do the wild man wanders in incident. I'm getting a similar error when dev moding the refugee pod incident to fire.

It was refugee pods that first alerted me to this, actually. In my game about half the pods would also cause the UI to completely disappear when the screen contained the square where the refugee was meant to be (they also didn't appear).

I'm assuming that as I'm the first to report this then either this has come about due to a recent change you've made, or else the problem is indeed on my end and I've got a very wonky install of RimWorld!

**Comment by jptrrs** [comment]
Thanks for reporting and isolating the error. I was able to pinpoint the cause (npcs generated without a faction) and correct it. A fix was just uploaded.
