### ISSUE TITLE
Another issue about settings and knowledge generation

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#116]
When starting a custom scenario with no technologies added and only "Knowledge generation draws from... ...the scenario starting research" option enabled, the error appears:
"[HumanResources] Couldn't calculate any expertise for PawnName"
And in some cases the same error appears when only "...the pawn's background" is enabled.

To be honest, I would like to play a character that starts with absolute nothing, so if this error is only informing that the knowledge generation failed and the lack of initial expertise will not be the cause of something bad in the future _(should I consider this message as a warning instead of an error then?)_, I'm fine with that.

**Comment by jptrrs** [comment]
Yeah, it is just an informative message. If you're aware you're going to
end up with an utterly useless colonist and you're prepared to deal with
it, you should be fine. Those options should not affect NPCs. But be aware
every new character the game eventually generates for your faction will get
the same treatment.

**Comment by Reiquard** [comment]
Your answer led me to believe that it is a mandatory requirement for expertise to have at least one learned technology so that the pawn becomes useful over time.
After a quick test the initially knowledge-empty pawn behaves as it should in the normal case (he researches, learns, and increases the techlevel of his knowledge)..
So I wondering is there anything else that should make that knowledge-empty pawn useless, or whether I misunderstood your statement:
"If you're aware you're going to end up with an utterly useless colonist and you're prepared to deal with it, you should be fine."

**Comment by jptrrs** [comment]
What I meant is the pawn would not be able to do any restricted tasks when the game starts, he would have to learn everything from scratch.
