### ISSUE TITLE
Tech tab not showing with Corruption(40k) mod

### ISSUE THREAD

**Issue by Spanish06** [jptrrs/HumanResources#117]
Compatibility issue with Corruption Core (40k) mod: Human (other races fine) pawns don't have Tech tab, instead they have Soul tab from Corruption mod.

**Comment by jptrrs** [comment]
Hi!
I tested the mod you mentioned and found no issues. You might be experiencing a conflict with another one. If so, please check [this procedure](https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/) to isolate it and gather the information I'll need. Thx.

![image](https://user-images.githubusercontent.com/47060670/102011503-54c0c000-3d23-11eb-9eab-ca397d3ac731.png)
![image](https://user-images.githubusercontent.com/47060670/102011536-918cb700-3d23-11eb-8de3-ba9f1c85a55c.png)
