### ISSUE TITLE
Recruiting morphed pawn breaks tech tree

### ISSUE THREAD

**Issue by trmplays** [jptrrs/HumanResources#123]
Basically title: tech tree works fine before recruiting morphed pawn.  After recruiting any morphed pawns (I tried it on multiple) it immediately breaks my tech tree and I get spammed with an error (screenshot attached).  Heres my logs as well: https://gist.github.com/7070a0ccfa9563c1c5260dccfe1f6a18

![log](https://user-images.githubusercontent.com/77560106/104829979-78998900-582e-11eb-92c2-edb8514047cd.png)

**Comment by trmplays** [comment]
I made a new save and tested it without prison labor as well, it still breaks the tech tree

**Comment by jptrrs** [comment]
Ok, Thanks for the game log, now know where to look.

**Comment by jptrrs** [comment]
After taking sometime to figure out how Pawnmorpher works, I managed to sucessfully reproduce the issue you're having. I can already tell what's wrong, but before designing a solution I wanted to ask you a couple things :
* Does it happen only with fully morphed pawns (i.e., those in a fully animal form)?
* Does it happen if you transform a human colonist all the way into an animal?

**Comment by trmplays** [comment]
Yes they must be in animal form.  Yes it happens if you transform a human colonist.

**Comment by trmplays** [comment]
Also once transformed into animal form they can use any weapons.  The Pawnmorpher mod for some reason allows transformed colonists to use weapons and I don't really get the reasoning behind this but it makes for some good memes i guess.  
![shotgun squirrel](https://user-images.githubusercontent.com/77560106/104871784-d8f8fb00-5900-11eb-80b8-dc8d802c851e.png)

**Comment by jptrrs** [comment]
Ok, thanks for the info. The issue was fixed on the latest version, 0.31.
I looked into allowing a fully transformed pawn to retain his knowledge, but that's not possible on our end. Now, they won't even show up on the research Tab, and adding this rule made HR a little bit more stable. Thank you!
