### ISSUE TITLE
An error on regenerating research tree layout (ResearchPal - Forked)

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#125]
Clicking on [Regenerate Research Tree Layout] button in the "ResearchPal - Forked" mod settings wipes all the settings elements and prints an error:
![screenshot32](https://user-images.githubusercontent.com/62316596/105495470-44f6ad00-5ccd-11eb-9827-74a4123f8ad1.png)

https://gist.github.com/486a4a6052f7ddefb9b8c4dd8e01935d

**Comment by jptrrs** [comment]
Thanks for testing. Fixed!
