### ISSUE TITLE
Cannot train weapons with Better Workbench Management copied recipes

### ISSUE THREAD

**Issue by peter-si** [jptrrs/HumanResources#126]
Hi, there seems to be a minor issue with [Better workbench management](https://steamcommunity.com/sharedfiles/filedetails/?id=935982361&searchtext=better+workbench) I just found. It seems, that when you copy your recipes pawns can't train. It writes something like `Cannot train wooden target stand: No available weapons to train`. It was a bit annoying to debug, so I figured I write it here. The workaround is just to set up each target stand separately (don't use better workbench management for them)

**Comment by jptrrs** [comment]
Hi peter, thanks for reporting. I tried replicating what you describe, but found no issues. Here are three colonists training with the same weapon on three copied recipes. 
![temp](https://user-images.githubusercontent.com/47060670/105629333-2e616a80-5e21-11eb-9ba6-e03127269559.png)
I'm running Better Workbench Management, ResearchPal and Human Reources here.
Maybe I'm missing something? It helps if you send me your log and list the steps you took to reproduce the issue. 
Thanks.

**Comment by jptrrs** [comment]
Closing for lack of response.
