### ISSUE TITLE
Can't Learn Melee Weapons With Alpha Animals

### ISSUE THREAD

**Issue by mothbooty** [jptrrs/HumanResources#132]
Hello,

This has already been somewhat discussed on the comments for the mod page on the workshop, but I figured I'd report that melee weapon learning is nonfunctional with Alpha Animals installed. Ranged weapons seem to work fine, but when a pawn with a melee weapon's tech learned tries to learn a new melee weapon from a tech, they repeatedly pick up the weapon, walk to the dummy, and drop it.

Unsure if this an issue on Human Resources' end, or AA, but I figured I'd report it nonetheless. No errors or anything are thrown.

**Comment by jptrrs** [comment]
Hi. Thanks for bringing this up. But without the game log my hands are tied. Please, check the instructions on how to produce it here: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by mothbooty** [comment]
Here's the log file, though it doesn't really say anything that I could notice that indicates Alpha Animals being the issue. However, I've had multiple people remove AA and have Human Resources' melee weapon training work perfectly after the fact, with and without Rimthreaded. https://gist.github.com/5f8776ce818652e61f524898d3d04817

**Comment by jptrrs** [comment]
This was before any game is actually initiated. Also, you loaded over 500 mods! Please, read those steps carefully. If you already suspect Alpha Animals, what's the diffculty of isolating it to reproduce the issue? Sorry, but I can't afford loosing time with this. Thanks.

**Comment by mothbooty** [comment]
I let a pawn run back and forth between a training dummy and a weapon at 3x speed for a while before uploading this log, so hopefully it provides more data. The mod list has been removed to just Alpha Animals, Human Resources, and a race with modded weapons that aren't learned at the start, the issue still happens. Issue can be reproduced by making a 75x75 map through quickstart, granting all research through dev mode, placing a study desk, training dummy, and any unlearned melee weapon that the tech is then studied afterwards. Pawn will study tech, then repeatedly move back and forth between the dummy and the weapon.

I'm starting to wonder if this is due to Vanilla Expanded Framework's implementation of a new Verb Framework for pawns in general, and if it's adversely affecting Human Resources.

This situation has also been tested without rimthreaded and can be recreated.

https://gist.github.com/ce62bf9f75abca341e7c4736ada10e65

**Comment by jptrrs** [comment]
Now we're talking!
Just to clarify, the issue is the pawn doesn't start training on its own? What happens if you try to force by right-clicking?

**Comment by mothbooty** [comment]
Tried doing that and the pawn does the same exact thing unfortunately. Even if their only job is set to Study.

**Comment by juanosarg** [comment]
Indeed, this is the MVCF in VE Framework, you should raise this there

**Comment by legodude17** [comment]
I think I fixed this in MVCF in [this commit](https://github.com/AndroidQuazar/VanillaExpandedFramework/commit/9bf42bc42c3272e88c00c60abc0505e70a7b7d8d).

**Comment by mothbooty** [comment]
I'll try out the new MVCF.dll after I get some sleep and report back.

**Comment by mothbooty** [comment]
Back from resting and figured I'd give an update: The update on the github works beautifully legodude, glad I was able to get ahold of you all to resolve this issue.

**Comment by jptrrs** [comment]
> 
> 
> Back from resting and figured I'd give an update: The update on the github works beautifully legodude, glad I was able to get ahold of you all to resolve this issue.

Me too!
