### ISSUE TITLE
Another error when trying to learn to shoot a weapon *sigh*

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#133]
Initial data:
 - Just-started "Lost tribe" scenario
 - God-mode-installed **[Target Stand]** with **"Learn to shoot a weapon"** bill _(all weapons are allowed)_
 - **Pawn1** (the one that _doesn't know_ how to shoot a **[Recurve Bow]** yet) is assigned to **"Study"** via work-tab
 - **Pawn1** is equipped with a **[Short Bow]**
 - **[Recurve bow]** spawned via Dev-Mode

Actions to reproduce:
 - Order **Pawn1** to **"Learn to shoot a weapon"**
 - While **Pawn1** is on its way to the **[Recurve bow]**, redraft it, or if you're already tired of pressing the R button, order it to perform any other task (consume pemmican for example), and the error will appear:

```
Verse.Pawn_EquipmentTracker container tried to drop  Bow_Recurve2529 which it didn't contain.
Verse.Log:Error(String, Boolean)
Verse.ThingOwner:TryDrop_NewTmp(Thing, IntVec3, Map, ThingPlaceMode, Thing&, Action`2, Predicate`1, Boolean)
Verse.ThingOwner`1:TryDrop(Thing, IntVec3, Map, ThingPlaceMode, ThingWithComps&, Action`2, Predicate`1)
Verse.Pawn_EquipmentTracker:TryDropEquipment(ThingWithComps, ThingWithComps&, IntVec3, Boolean)
HumanResources.JobDriver_LearnWeapon:<MakeNewToils>b__16_2()
Verse.AI.JobDriver:Cleanup(JobCondition)
Verse.AI.Pawn_JobTracker:CleanupCurrentJob(JobCondition, Boolean, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
RimWorld.Pawn_DraftController:set_Drafted(Boolean)
RimWorld.Pawn_DraftController:<GetGizmos>b__13_1()
Verse.Command_Toggle:ProcessInput(Event)
Verse.GizmoGridDrawer:DrawGizmoGrid(IEnumerable`1, Single, Gizmo&)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1, Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:Verse.Root.OnGUI_Patch1(Root)
```
This error will be repeated each time we draft (entering in the draft state) a pawn or by some other means cancel its current "Learn to shoot a weapon" job, while the pawn is equipped with a weapon and is on its way to the weapon it wants to learn.

 - HR is updated to the latest HiTechResearch version

https://gist.github.com/09965119deba7adfcaf2c3e56c90c656

**Comment by jptrrs** [comment]
That's what you get by testing an unfinished mod... Thanks! Now let's see what's the next Draft-related error you'll find ;-)
