### ISSUE TITLE
HiTechResearch: Inability to document neolithic technology in the Crashlanded scenario (and crucial error on save/load)

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#134]
- Started "Crashlanded" scenario
 - Assigned **Cahuella** to research **[Beer brewing]**
 - Waited until the research was completed
 - Assigned **Cahuella** to document **[Beer brewing]**
 - Tried to order **Cahuella** to document **[Beer brewing]**
 - Got this _JobFailReason_:

![screenshot3](https://user-images.githubusercontent.com/62316596/107434119-5e0bb480-6b3b-11eb-8f60-100d4fac8d54.png)

When assigning **Cahuella** to document **[Psychite refining]** (or more widely any other **industrial** technology), such a situation does not occur:
![screenshot5](https://user-images.githubusercontent.com/62316596/107435879-ceb3d080-6b3d-11eb-88a7-45c9caf95ee9.png)

_Tried later to reproduce this in "Lost tribe" scenario, but everything went as it should._

### The crucial error

When saving this game (the game was paused at that moment when I was taking screenshots), I got this error:
```
Exception while saving Cahuella: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x0004e] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at HumanResources.CompKnowledge.PostExposeData () [0x00074] in <7fbffab2428e4f4081eb05144c998b12>:0 
  at Verse.ThingWithComps.ExposeData () [0x0002c] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Pawn.ExposeData () [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Scribe_Deep.Look[T] (T& target, System.Boolean saveDestroyedThings, System.String label, System.Object[] ctorArgs) [0x0016a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Error(String, Boolean)
Verse.Scribe_Deep:Look(Thing&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Thing&, String, Object[])
Verse.Map:ExposeData()
Verse.Scribe_Deep:Look(Map&, Boolean, String, Object[])
Verse.Scribe_Collections:Look(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:Look(List`1&, String, LookMode, Object[])
Verse.Game:ExposeData()
Verse.Scribe_Deep:Look(Game&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Game&, String, Object[])
Verse.<>c:<SaveGame>b__13_0()
Verse.SafeSaver:DoSave(String, String, Action)
Verse.SafeSaver:Save(String, String, Action, Boolean)
Verse.GameDataSaveLoader:SaveGame(String)
RimWorld.<>c__DisplayClass3_0:<DoFileInteraction>b__0()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
```

https://gist.github.com/fd59efc3d8ded5820848916555a50510

After loading the saved game, **Cahuella** **_was missing_** and I got these errors:
https://gist.github.com/51658a6b5ea2fb0c8153c7a5452ae141

_P.S._
Should I keep creating new issues if I find new bugs? I'm beginning to think you've had enough of me ;)

**Comment by jptrrs** [comment]
>P.S. Should I keep creating new issues if I find new bugs? I'm beginning to think you've had enough of me ;)

Well, if you keep finding them, yes! This was a good one. The problem was actually a little deeper: some changes I made on this branch were preventing the pawns from correctly learning the technologies when researching them. Later, the corrupted record would cause these issues you were having.
