### ISSUE TITLE
Technical book as a quest requirement.

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#136]
I just got a quest that requires 4x **[Technical book]** to complete.
The quest is _TraderShipsTradeRequest_ from ["Trader ships"](https://steamcommunity.com/sharedfiles/filedetails/?id=2046222331) mod, similar to vanilla _TradeRequest_.
The problem is that there can be no such items at the player's disposal.

_HR is at latest master-branch_

**Comment by jptrrs** [comment]
Yes, there is! You just need to give up four books!

**Comment by Reiquard** [comment]
> You just need to give up four books!

I'm not sure what did you meant, but I spawned via dev-mode tons of these books (which turned onto various stuffed books)
and there is still unfulfilled requirement of 4x [Technical book]

![image](https://user-images.githubusercontent.com/62316596/108004015-a2002d00-7005-11eb-9b75-4c64abd35b97.png)

![image](https://user-images.githubusercontent.com/62316596/108003892-35852e00-7005-11eb-8795-fddef11bdf4c.png)

**Comment by jptrrs** [comment]
Did you try putting them into a stockpile?

**Comment by Reiquard** [comment]
Just tried with a stockpile, home area and stockpile+home area - the requirement is still unfulfilled

**Comment by jptrrs** [comment]
I just tried editing an existing vanilla trade request to ask for books. Then I managed to sucessfully accept and deliver the requested items and completed the quest with no issues. So it looks like it's an issue with that particular mod... 
Not sure there's anything I can do.
