### ISSUE TITLE
Glitches in the research window

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#137]
Research nodes are truncated on the right side of the research window regardless of the zoom level_(pointer 1)_.
Not a big deal, but the book image overlaps with some of the research window elements _(pointer 2)_.
![p1](https://user-images.githubusercontent.com/62316596/107930184-b30c5800-6f8b-11eb-979d-f6dcbbc8ce72.png)

In addition, switching from the research window to the pawn's tech-tab leads to a wider display of technology cards (which return to the original width after a while).
![p2](https://user-images.githubusercontent.com/62316596/107946449-199c7080-6fa2-11eb-9847-e3da1ec817ea.png)

activeMods
      - brrainz.harmony
      - ludeon.rimworld
      - ludeon.rimworld.royalty
      - unlimitedhugs.hugslib
      - fluffy.modmanager
      - vinalx.researchpalforked
      - jpt.humanresources   _(latest master)_
/activeMods

**Comment by jptrrs** [comment]
Pointer 2 is unfixable, as far as I'm aware. It's a quirk from the Unity function rimworld uses to display icons colored by material. Between this and having the book colors hard-coded or omitted, I prefer to live with it.
Pointer 1 is more concerning. What are your screen resolutions and UI scale?

**Comment by Reiquard** [comment]
> What are your screen resolutions and UI scale?

 - 1920x1080 (1080p)
 - 1x
