### ISSUE TITLE
Knowledge on servers does not persist through saves

### ISSUE THREAD

**Issue by Afterthought-btw** [jptrrs/HumanResources#142]
Exactly what it says on the tin, really. Easily repeatable with nothing but HR's required mods: 

Start a new game. Gift yourself a server, a terminal, and some books through dev mode. 

Scan the books into the server.

Save game.

Load game you just saved. 

Books are no longer on the server and have to be rescanned. (Or rewritten, presumably, if you no longer have the books for w/ever reason.)

**Comment by jptrrs** [comment]
Thanks for reporting. Some last minute changes had disrupted the saving process. :-\ Fixed for the next update.
