### ISSUE TITLE
Pawn frozen while trying to document a tech (& Exception)

### ISSUE THREAD

**Issue by vsaulue** [jptrrs/HumanResources#143]
### What's happening

A pawn attempts to document some spacer tech on a study bench, throwing exceptions. The game repeatedly tries to queue this invalid documentation task on every tick, leaving the pawn stuck doing nothing.

**Main errors:**

```
Exception ticking Gawen (at (158, 0, 169)): System.ArgumentNullException: Value cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00008] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Verse.GenCollection.TryGetValue[T,V] (System.Collections.Generic.IDictionary`2[TKey,TValue] dict, T key, V fallback) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at HumanResources.JobDriver_DocumentTech.TryMakePreToilReservations (System.Boolean errorOnFailed) [0x00043] in <d5067b80eea44b50b6f7403aed5bedbb>:0 
  at (wrapper dynamic-method) Verse.AI.Pawn_JobTracker.Verse.AI.Pawn_JobTracker.StartJob_Patch1(Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
  at Verse.AI.Pawn_JobTracker.TryFindAndStartJob () [0x000bd] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.AI.Pawn_JobTracker.Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch2(Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
  at Verse.AI.Pawn_JobTracker.JobTrackerTick () [0x00151] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Pawn.Tick () [0x00098] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.TickList.Tick () [0x0015c] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch2(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch2(Game)
Verse.Root_Play:Update()

Gawen started 10 jobs in 10 ticks. List: (Wait_MaintainPosture (Job_13474288)) , (Wait_MaintainPosture (Job_13474290)) , (Wait_MaintainPosture (Job_13474292)) , (Wait_MaintainPosture (Job_13474294)) , (Wait_MaintainPosture (Job_13474296)) , (Wait_MaintainPosture (Job_13474298)) , (Wait_MaintainPosture (Job_13474300)) , (Wait_MaintainPosture (Job_13474305)) , (Wait_MaintainPosture (Job_13474308)) , (Wait_MaintainPosture (Job_13474310))  curDriver=JobDriver_WaitMaintainPosture (toilIndex=0) curJob=(Wait_MaintainPosture (Job_13474310))
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch2(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch2(Game)
Verse.Root_Play:Update()
```

**[+ full log](https://gist.github.com/HugsLibRecordKeeper/cbd58523a58330957b38f4b4f5f11573)**

**Additional info:**

* The pawn seems to try to document "ResearchProject_RTCircuitBreakers" from [RT Fuse](https://steamcommunity.com/sharedfiles/filedetails/?id=728314182), which is spacer tech. For some reason, the game still tries to document it on a study bench.
* Disabling "Industrial" techs from being documented on the study bench prevents the job from being queued.
* This game was started before the recent update with the servers (maybe a migration problem ?).

**Maybe related** (same stacktrace): [Error when documenting tech](https://github.com/jptrrs/HumanResources/issues/81).

### Steps to reproduce:

I've failed all my attempts at reproducing on a new lightly modded game. All I can do is upload my main savefile for now, which remains bugged.

* Load the [savefile](https://github.com/jptrrs/HumanResources/files/6022788/Savefile.zip) (after unzipping) with this [modlist](https://github.com/jptrrs/HumanResources/files/6022781/Modlist.txt) (latest versions from the Steam workshop).
* The error should happen instantly, and keep repeating itself. The "Gawen" pawn is stuck.

**Comment by jptrrs** [comment]
Thanks for reporting and coming up with this detailed information on the error context. It was very helpful in understanding what was going on. 
Yes, this looks like a migration issue. It seems like your pawn was about to start to write that tech down when the file was saved, but after the update it can no longer be done at the regular study desk. You'd need a network terminal and a server. This nullifies the selected tech, causing the job to fail before it even started. I'll see if there's a way to prevent this from happening in the future, as there are other saving/loading situations that could cause the same deadlock. But as for your save file, the fix is pretty simple:
1. Go to Options and turn on Development mode.
2. Open the debug actions menu, on the fourth little icon that appear on the top of your screen.
3. Search for "EndCurrentjob(InterruptForced)" and select that.
4. Click on the affected pawn.
On my tests, there were no residual issues.

**Comment by vsaulue** [comment]
Hi, thanks for the quick answer !

Your fix doesn't solve my issue: the game keeps trying to requeue the exact same job again. No worry for my savefile: for now I just removed the tech from the list of things to document.

After some further testing, it's not a migration issue. I was able to reproduce on a new game with Vanilla techs only.

### Root cause

The bugged pawn:

* Has Study work with higher priority than the Research work.
* Knows a spacer tech, and is set to document it.
* Has a pre-spacer tech to research.

From what I see in the source code and the savefiles: both the technologies to document, and the techologies to research ends up in the same "homework" list. It looks like this specific situation confuses the "document" workgiver/jobdriver...

### Steps to reproduce (v2):

* Create a new game with this [modlist](https://github.com/jptrrs/HumanResources/files/6025350/Modlist.txt) (quick game from the debug menu works fine).
* Make
  * a study table with "Document Technology" forever
  * a study table with "Study Technology" forever
  * a hi-tech research bench
  * multi analyzer
  * power source
![image](https://user-images.githubusercontent.com/34475300/108775490-6a433900-7561-11eb-8b3b-e832ce5d37e9.png)
* Edit a pawn's work tab:  Research prio 2, Study prio 1.
![image](https://user-images.githubusercontent.com/34475300/108775383-4a137a00-7561-11eb-8c4f-fb3da28dffd0.png)
* Make this pawn research any spacer tech (ex: cryptosleep casket). Wait until finish.
* (optional/situational) use debug tools to kill your other pyromaniac pawn attempting to destroy the lab (because Rimworld).
* After that, make the "good" pawn research any lower-than-spacer tech (ex: Tree sowing).
* The pawn will be stuck "standing", throwing the exception in loop.

**See:**
[zipped savefile](https://github.com/jptrrs/HumanResources/files/6025462/HR.bug.zip) (it should throw the exception when loaded)
[full log](https://gist.github.com/HugsLibRecordKeeper/618f911b4c5f5bc30928ccebbac8125f)

**Comment by jptrrs** [comment]
You're right! That set of projects on the homework was confusing the document WorkGiver. But it was just poorly equipped to handling the new bill filters. It's fixed, I'm updating the mod now.
