### ISSUE TITLE
Experiment with SOS2 disassembler mechanites issue

### ISSUE THREAD

**Issue by tophd7** [jptrrs/HumanResources#145]
Log: https://gist.github.com/8c7c95a8fac691b91b9f06dcd48d19d4
![Screenshot 2021-03-06 200414](https://user-images.githubusercontent.com/62030922/110225839-27fdee00-7eb7-11eb-9a92-2e0249604b69.png)
Not quite sure how this happens but I had 8, pawn was experimenting (pawns failed it twice but this didn't happen) then my screen started shaking then fps dropped so I started looking around to see what was happening and found this..

**Comment by jptrrs** [comment]
That doesn't look good. But from your log, I'm not sure it has anything to do with Human Resources. We would need a way to reproduce it before calling it an issue. Please check these instructions on how to isolate and report it:
https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by jptrrs** [comment]
Presumed irrelevant.
