### ISSUE TITLE
OnDefsLoaded's MissingMethodException for 1.2 and 1.3

### ISSUE THREAD

**Issue by Krelinos** [jptrrs/HumanResources#160]
Playing 1.2 and receiving an error right at the main menu. No mods nor Royalty. Tech tab for colonists is missing and cannot select a research for them to pursue.

https://gist.github.com/536d2b72846600c13c9e8a9798c1e351

In addition, another user on the Steam comments of the error reporting has posted the same thing for 1.3 with no mods and both DLCs.

https://gist.github.com/063b330c159a4e1f5bb9fca9089e4353

Notably, the error is logged on Line 84 for both logs, but my 1.2 log and their 1.3 log have different messages.

**Comment by jptrrs** [comment]
Hah! I knew there were people still playing on 1.2! Glad I decided to keep
the mods multi-version.
Unfortunately, it seems I missed something with the way HugsLib updated its
1.2 version (It's not the same issue reported on Steam). I'm going to have
to check it out.
In the meantime, you can use the previous stable version. It's functionally
identical to this latest update:
https://github.com/jptrrs/HumanResources/releases/tag/v0.39

**Comment by Krelinos** [comment]
Awesome, thank ya!

**Comment by jptrrs** [comment]
Fixed it on version 1.0.3.
