### ISSUE TITLE
Research Pal Forked Issue

### ISSUE THREAD

**Issue by Zero-Requiem22** [jptrrs/HumanResources#162]
Hello, I'm having an issue with the research screen with Research-Pal and for some reason, I can't pan around the screen at all, the only thing that works is zooming in and out at one spot. It happens when I right-click on a technology through the tech tab from a pawn's knowledge.

I tested it with a bare minimum list and I wouldn't get any errors but the issue still occurs.

https://gist.github.com/49c257c7c8f19e755fb789935e1ac809

**Comment by jptrrs** [comment]
Thanks for reporting. I can confirm the issue, but it only happens when accessing the research screen by right-clicking on the tech tab. That's most likely due to some recent change on ResearchPal - Forked. I'll see what I can do.

**Comment by Zero-Requiem22** [comment]
Ok, Thank you for taking alook! Hopefully, the issue can be resolved!

**Comment by Ren-agade** [comment]
I cleared this problem by scrolling over the pawn icons in the top right. They were hidden under the Learning helper.  
Seems to constantly fix the issue.

**Comment by jptrrs** [comment]
[Ren-agade](https://github.com/Ren-agade)

> I cleared this problem by scrolling over the pawn icons in the top right. They were hidden under the Learning helper. Seems to constantly fix the issue.

This was a very useful finding! I was able to narrow it down. But I'm still working on a solution...

**Comment by jptrrs** [comment]
Fixed for the next update.
