### ISSUE TITLE
Queue Issue with Research Pal Forked

### ISSUE THREAD

**Issue by Zero-Requiem22** [jptrrs/HumanResources#163]
Sorry to bother you again, but I noticed an Issue with Research Pal-Forked in the senes that its research queue feature is not working with Human Resources. Im using a minimal modlist and confirmed it was HR.
https://gist.github.com/f5cdaabf2d2b19c578ed8126090f79a8

**Comment by jptrrs** [comment]
How exactly do you expect it to work, when researching is an individual affair for each pawn?

**Comment by Zero-Requiem22** [comment]
Hmm, that is true. And I realized that there is a queue per pawn in their respective tech tab. My apologies for all of this mate.

**Comment by jptrrs** [comment]
;-)
