### ISSUE TITLE
Unable to Study or Document Tech

### ISSUE THREAD

**Issue by Blunthammer** [jptrrs/HumanResources#169]
I am unable to figure out which mod is causing this, but after a certain period of time, pawns will not study or document at all. When attempting to force them, get a message on right click that they have nothing to study, go to main research tab. Have tried clearing all techs up for documentation then re selecting them, but same message.

**Comment by jptrrs** [comment]
I need a way to reproduce the issue before I can help. For that, I absolutely need all the information I describe here: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/
Do you get the issue when starting  a new game? I'd start there, then trying to isolate any possible mod conflicts.
