### ISSUE TITLE
Possible issue with HR and ammo mods

### ISSUE THREAD

**Issue by Blunthammer** [jptrrs/HumanResources#170]
I am unable to have pawns learn weapons that use ammo(Yayo's Combat, All Bullets Matter) on the shooting range. Because the weapon is empty, it does not show up as a valid weapon to use. Even when pawn is carrying ammo, they will not reload it. Don't know if this is something you could fix or if it has to be the ammo mod makers.

**Comment by jptrrs** [comment]
Log? Links? Please follow: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by Blunthammer** [comment]
https://gist.github.com/0f38adfb79983c23fa8855f6c64640e2 
Logs

**Comment by ShauaPuta** [comment]
hi, I have the same issue the person above reported with Yayo combat 3 (link https://steamcommunity.com/workshop/filedetails/?id=2513695736 )
some modded weapons (like forsaken bows, from forsakens (link https://steamcommunity.com/sharedfiles/filedetails/?id=1728999127 )) when without ammo cannot be used on targets to train the use of the weapon, even if the pawn has the research knowledge
meanwhile, some other weapons like vanilla grenades and medieval times's guns can be used to train, even without ammo

**Comment by ShauaPuta** [comment]
update on my part: even with ammo, some modded weapons cannot be trained with. The ones I noticed where forsaken bows (mentioned above), war bows from tribal warrior set (https://steamcommunity.com/sharedfiles/filedetails/?id=2401466559) and elven bows from lord of the rims (https://steamcommunity.com/sharedfiles/filedetails/?id=1400234784)
issue still seem to come from yayo combat 3

**Comment by jptrrs** [comment]
Thanks for the link, ShauaPuta. I found no issues with that mod. Here's a tribal pawn learning to shoot with an assault rifle:
![image](https://user-images.githubusercontent.com/47060670/170318868-c514fd97-2634-4d11-adc3-6a19f860f2bd.png)
About the other modded weapons, I answered on issue #172.

**Comment by jptrrs** [comment]
> https://gist.github.com/0f38adfb79983c23fa8855f6c64640e2 Logs

There were over 300 mods loaded here, making it completely useless. Please read and follow these instructions for reporting issues:  https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/
