### ISSUE TITLE
Can't operate Rimatomics weapons console

### ISSUE THREAD

**Issue by Vladorio** [jptrrs/HumanResources#173]
Option "operate console" don't appear on the right click (even inactive, as for mortar)

Right click menu can appear with "repair" or "disassemble" weapons console, but never - with "operate" choice.

Tested with no other mods:
https://gist.github.com/de913144a89aa8c3cedec2e9f60b9d9a

Tested with/without HumanResources on same save. Issue appears only while HumanResources is active.

**Comment by jptrrs** [comment]
Log? Links? Please follow: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by Vladorio** [comment]
Rimatomics?
Here: https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465

**Comment by jptrrs** [comment]
Thanks. It will be fixed on the next update.

**Comment by jptrrs** [comment]
Mod updated on Steam.
