### ISSUE TITLE
Cannot document Electricity?

### ISSUE THREAD

**Issue by SolariusScorch** [jptrrs/HumanResources#178]
Not sure if a bug (very unlikely), mod conflict (possibly) or me not understanding things (most probably), but I cannot document Electricity. This should be allowed by the desk, the pawn knows the tech, it is also researched (starting tech for my game), and there is a bill open. Please check attached screenshot for details.
The message says that Aeja has no projects assigned, but after much time of browsing the github wiki and looking for options in the game I haven't found anything relevant.
(I researched a different tech before and it made it into the book, so the mod certainly works.)
![HR_issue](https://user-images.githubusercontent.com/7339969/177551347-2339a872-4249-472e-9fa0-569ce44d82fb.jpg)
Your help would be most appreciated!

**Comment by ZXfkSIE** [comment]
Starting techs do not need to be documented. It is integrated in your study desk.
Just study it.

**Comment by jptrrs** [comment]
Thanks, @ZXfkSIE !
Also, that answer is on our wiki: https://github.com/jptrrs/HumanResources/wiki/FAQ#q-why-cant-i-assign-my-pawn-to-document-a-certain-tech-he-knows

**Comment by SolariusScorch** [comment]
All right, thank you guys. Indeed I saw this part, but didn't connect it with my problem.
Frankly, I think this should be documented better; I tried to familiarise myself with the process, but still mostly clicked blindly, and after several days I still have more assumptions than knowledge. :P
I appreciate the help!

**Comment by jptrrs** [comment]
> I think this should be documented better; I tried to familiarise myself with the process, but still mostly clicked blindly, and after several days I still have more assumptions than knowledge.

Well, I wrote the guide to the best of my ability, but I'm not a professional. There's probably room for improvement. From your experience, where should this information be so it would be found more easily?

**Comment by SolariusScorch** [comment]
> Well, I wrote the guide to the best of my ability, but I'm not a professional. There's probably room for improvement. From your experience, where should this information be so it would be found more easily?

I think adding a note to The Study Desk would be fine. Something like: "Note that you only need to document research projects you haven't started the game with; starting techs are automatically considered documented."

**Comment by jptrrs** [comment]
> > Well, I wrote the guide to the best of my ability, but I'm not a professional. There's probably room for improvement. From your experience, where should this information be so it would be found more easily?
> 
> I think adding a note to The Study Desk would be fine. Something like: "Note that you only need to document research projects you haven't started the game with; starting techs are automatically considered documented."

Perfect. Done!

**Comment by SolariusScorch** [comment]
Many thanks! Love your mod!
