### ISSUE TITLE
Bookshelf despawned after loading a save file

### ISSUE THREAD

**Issue by rimpy-custom** [jptrrs/HumanResources#179]
Have also reported issue in Steam, but got instructions to post issue here too.
Somehow my bookshelves got despawned during loading save file. First time I thought that book shelf was destroyed, but second time I got this error: [https://gist.github.com/a15970bc5d50d98068e8af1a40a00a09](https://steamcommunity.com/linkfilter/?url=https://gist.github.com/a15970bc5d50d98068e8af1a40a00a09)
Some how simple meal got stored in book shelf, probably that caused issues. Not sure about first disappeared book shelf, because I was raided and it really might get destroyed.

UPD: I have found save file where first bookshelf disappeared. The same issue, but with different item. It got knife into storage, somehow. Here is part of save file for bugged book shelf (first one): [https://rentry.co/9ozky](https://steamcommunity.com/linkfilter/?url=https://rentry.co/9ozky)
And here is the second one (with simple meal): [https://rentry.co/cw7tu](https://steamcommunity.com/linkfilter/?url=https://rentry.co/cw7tu)

Idk how that has happened. Might be pick up and haul, somehow or other mod conflict. May it be possible to filter things on save file loading to purge any item except text book on book shelves or handle issue in different way.

**Comment by jptrrs** [comment]
Thanks for bringing it up, Paladin. This issue was already reported on #168 and I'm currently waiting for someone who's experiencing it to isolate the conflicting mod. If you could help, it would be awesome.
