### ISSUE TITLE
Incompatiblity with Ammunition mods

### ISSUE THREAD

**Issue by jptrrs** [jptrrs/HumanResources#18]
Omg doesn't work with ammunition at all!!
crowberry:

When I put my pawns to learn to shoot a new weapon on the target stand, the ammunition they are holding runs out just straight down to zero, without a single shot taken. I can see the numbers go down just really quick, no matter if the ammunition is in their inventory or in an ammo pack. Then they run out of ammunition and stop learning the new weapon. Endless waste of ammunition without any learning.

To counter this I have to exclude current weapons to learn from the ammunition mod options, so that they don't use ammunition, then learning works.

Also, gunplay mod animations don't run while learning a weapon.

So, mod incompatibility with LimeTreeSnake's Ammunition and AUTOMATIC's Gunplay.

**Comment by jptrrs** [comment]
Acorn:
Mod incompatibility. [Ammunition mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1892397131). It's a mod that adds simple ammo to all ranged weapons. It prevents colonists from learning new and/or practicing at ranged target. Ammo in colonist's inventory are all spent in one go without actually firing the weapon and forces colonist to drop weapon. Rinse & repeat.

Work around: As crowberry mentioned above, disabling specific weapons from using ammo for brief time colonist is learning/practicing the weapon allows things to go through.

I'm not familiar with coding but from what I can guess it's due to learning new weapon and practicing requires colonists to actually "use" said weapon while performing the bill. Could possibly be patched if practice range bill doesn't use actual weapon...?

I know there's probably million other things you want to work on rather than go after individual mod compatibility support so just thought I'd put it in here as well to note that other people know such incompatibility exists.

**Comment by jptrrs** [comment]
Frazzled :
Minor conflict with Bullet Casings mod. Training to use a gun at the shooting target will near instantly litter the area with bullet casings -- the gun seems to be considered as being fired infinitely quickly, regardless of its actual fire rate.

**Comment by ELLIOTTCABLE** [comment]
It looks like you already closed this out; but one more "weird weapon-learning-triggering-other-mods-infinitely-quickly" effect I recall is with Children School and Learning(I think? or one of the other children-adding mods?) - if attempting to shoot a weapon that's too "large" for them, children/teens will receive a bruise or cut. The weapon-learning causes them, as soon as they walk up to the weapons stand, to instantly receive a huge number of bruises/cuts and become downed.

Just one more mod worth testing against!
