### ISSUE TITLE
Option to not generate default knowledge for pawns at all?

### ISSUE THREAD

**Issue by DarkShadow44** [jptrrs/HumanResources#184]
I'd prefer now having my recruits have random technologies, forcing normal research.

**Comment by jptrrs** [comment]
This is not an issue, so it doesn't belong here.

**Comment by DarkShadow44** [comment]
Usually github issues are also for suggestions, where should I put suggestions?

**Comment by jptrrs** [comment]
Steam comments, please. 
But TBH, that sort of thing was something I would consider while the the mod was being developed. But It has reached its final form for a while now.
