### ISSUE TITLE
Can't Do Any Research Requiring High Tech Research Bench 

### ISSUE THREAD

**Issue by Americangrit1** [jptrrs/HumanResources#36]
So I started a clean game with the bare mods + a Mod Manager/Royalty (those didn't affect this issue I tested this issue separately and it appeared without the Mod Manager and without Royalty) and I can't research anything that requires a high tech research bench. I  tested this trying to get a pawn to research the Multi Analyzer and confirmed the pawn already knew Electricity and Microelectronics first.  It did not give me any errors when I tried to force pawn to research Multi Analyzer, it just kept saying "Cannot research steel high-tech research bench: [Pawn name] has read all the books." 

Logs below:
https://gist.github.com/a476b5eb8280b104fbbca63a23facd45

**Comment by jptrrs** [comment]
We just fixed it ;-)
