### ISSUE TITLE
Incompatibility with Recipe icons

### ISSUE THREAD

**Issue by MinerSebas** [jptrrs/HumanResources#39]
This Mod adds a Preview of potential resources used and gained of a Recipe. When this mod is active and you try to add either the Research Tech or Document Tech recipes, then are errors thrown.
Both RecipeDef's have a TechBook as their Product defined, which I think is the cause of this error.

Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195

Error Log: https://gist.github.com/badb7cfcd1c7d26801498de0f7a9043e

**Comment by jptrrs** [comment]
Fixed for next update.
