### ISSUE TITLE
Mod conflict: Expanded Rims

### ISSUE THREAD

**Issue by seona13** [jptrrs/HumanResources#4]
I discovered that [Expanded Rims](https://steamcommunity.com/sharedfiles/filedetails/?id=1643536285) does not play nicely with Human Resources - the "Research technologies" job on the Research Bench does not show a list of possible technologies when you go into Details.

Is there anything I can send you to make it easier for you to narrow down what might be causing the problem?

**Comment by jptrrs** [comment]
Yes, there is! Hit Ctrl+F12 to upload your log and send me that link. Thanks!

**Comment by jptrrs** [comment]
Yes, hit Ctrl+F12 when the error pops up, upload the log and send me that
link!

João Pedro

**Comment by jptrrs** [comment]
I tested this and couldn't reproduce the issue. If you're still getting it, send me the log and we'll work it out.
