### ISSUE TITLE
Colonists can wear untrained weapons through caravan gathering.

### ISSUE THREAD

**Issue by ZXfkSIE** [jptrrs/HumanResources#42]
You indeed have done good jobs to fix the backdoor of Simple Sidearms.
However, colonists can gather untrained weapons to their inventory.
Then they can use it through the weapon change key of Simple Sidearms.

**Comment by jptrrs** [comment]
Yeah, I know. That's the issue remaining to fix for SS I mentioned on the
change notes. It should happen further down the line.
Thanks for reporting, anyway.
João Pedro
