### ISSUE TITLE
EdB Prepare Carefully compatibility request [Workaround]

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#44]
There is a minor issue with EdB Prepare Carefully.  If you add weapons to your equipment when you prepare carefully, those weapons will not get added to the pawns weapons, and they will have no ability to use them.

As a workaround, it's fairly straightforward to add new weapons to the pawns through save file editing.  Annoying, but not game-breaking.

On the upside, I also found out that having multiple identical weapons that are known causes no identifiable issues, and dissapears from the save file on a load & new save sequence.

**Comment by jptrrs** [comment]
Thanks for reporting this, I will look into it. It should be an easy fix.
João Pedro

**Comment by jptrrs** [comment]
I realized I misunderstod, I thought you were using Prepare Carefully to add equipment directly to your pawns somehow! 
No, that's a designed feature. But.... I decided to include an option to the settings panel that does what you ask. Will be up on the next update, stay tuned! ;-)
