### ISSUE TITLE
Initially known Technology Options [Feature Requests]

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#45]
So, like many of us, I play a heavily modded game.  This means that I have quite a number of added technologies.  Just shy of 800 in my current game.

So, my thing is that when I start a new game, say, with industrial background (Where most of the tech's are), I get a random smörgåsbord of techs that the pawns know.  Three each.

Well, it'd be nice if this number could be changed, at least for the original colonists.  Any other pawns, I could see 3 or even 2 being best, as it's fairly easy to 'farm' them for research via the prison labor mod, but that's an unintended consequence.  If it's possible to make this a chooseable value, it'd be nice if it could be separated for original vs 'new' Pawns.  Lastly, maybe a modifier based on the initial Tech Level of the pawn?  So maybe the player could say that Neolithic Pawns get +2 techs, Medieval get -1, Industrial stay the same, Modern +1, Spacer +2 and Glitter -1?

Here are a couple of things that I think would also be neat.

Partially known technologies.  Somebody shows up, and they know a bit about something, but they don't know everything.  Or maybe the know a fair bit, but it's spread out.  A bit here and there, with the total amount known of all techs adding up to a specific amount as decided above.  Say, if the Pawn knows a total of 2 techs, maybe 1 in Passive Cooler, .75 in Beer Brewing, and .25 in Pemmican?  Maybe only make it so that all but the last whole tech gets spread out?  It'd reduce the insta-gain of a whole bunch of techs for "free" from your starting pawns, as they only need to record their knowledge, rather than research it in the first place.

A range of amount known.  Say, something like if you want to have an average of 3 known techs, get two random numbers from 0 to 1, sum them, then multiply them by 3?  You get a nice binomial distribution, and fractions could be dealt with as above?

Somehow make the amount known weighted and/or distributed also by the Intellectual skill & passion of the pawn?

The ability to have a left-sided distribution of techs (of the Tech Level that you start with.)  So if a pawn is going to start with 3 Medieval Techs, maybe have a recursive 75% re-roll if that tech also has a prerequisite that is medieval, and to take that prerequisite instead?  From a progression standpoint, I think this might make sense.

A chance if you have a Natural Meditation Focus, from a tribal background, to have a chance to start with a Neolithic technology instead of one from your appropriate tech level.  I can't think of a way that it would easily doable for other backgrounds, especially with other mods, but it might be possible with a check for Neolithic & Natural Focus, as that's something that other mod authors would need to fix, not you.  I think this would be nice, as then you'd get some pawns that seemingly did the whole "Primitive Technology"-youtube binge before they showed up.

And last, and off topic but I didn't want to make another post, maybe an option to hide or collapse all techs of a specific tech level, if a pawn knows all of them?  Maybe tie this into a code 'do I know this thing' check as well, so that it's easier to iterate over the list?  Code-wise it might make more sense to break it up by mod, I don't know.  That seems a bit less useful, especially since most mods spread their techs over many levels.  A binary tree might work, but that'd be hellish to implement.  Don't really worry about this last suggestion, as I know from experience that coding for efficiency adds tonnes of technical debt later down the line.

**Comment by jptrrs** [comment]
Great ideas, chrispikula! I'll make sure to consider them before doing another update. Some aren't hard to implement at all! Some considerations:

> So, my thing is that when I start a new game, say, with industrial background (Where most of the tech's are), I get a random smörgåsbord of techs that the pawns know. Three each.
- I have considered making that number customizable, but I'm sure people would just abuse this, which would ruin the experience. I'm not ruling that out yet, but I'd rather find ways to achieve the same result by other means. One thing I did was making the tech pool from which the initial expertise is sorted for the player's pawns to be configurable. Have you seen that option on the settings panel? If you want to, you can focus them to the faction's starting research instead of their tech level. That wound narrow it down to more useful techs. And you can also include additional starting techs to the scenario, those are also added to the mix.

>  Lastly, maybe a modifier based on the initial Tech Level of the pawn? So maybe the player could say that Neolithic Pawns get +2 techs, Medieval get -1, Industrial stay the same, Modern +1, Spacer +2 and Glitter -1?
- I'm also planning on writing down an explanation of how the mod calculates how many starting techs each pawn gets, so people get a hold on what's at stake. It is tech-level-based! But is more like Neolithic & Medieval is 0 , Industrial -1 and anything above that -2. The number is further modified by age and the skills the pawn is better at. Highly Intellectual pawns do get an edge, and passion is used to untie between same-level skills. If you can read code, its all [here](https://github.com/jptrrs/HumanResources/blob/master/Source/Knowledge/CompKnowledge.cs), on the GetExpertiseDefsFor method. 

> Partially known technologies. 
- A little harder to implement, but its a good idea.

> The ability to have a left-sided distribution of techs (of the Tech Level that you start with.) So if a pawn is going to start with 3 Medieval Techs, maybe have a recursive 75% re-roll if that tech also has a prerequisite that is medieval, and to take that prerequisite instead? From a progression standpoint, I think this might make sense.
- It does make a lot of sense.

> A chance if you have a Natural Meditation Focus, from a tribal background, to have a chance to start with a Neolithic technology instead of one from your appropriate tech level.
- I'm currently looking into taking advantage of the system that ties Meditaion Focus into a pawns background. We already search for key words on npcs backgrounds in order to determine his tech-level when that information can't be extracted from his faction. I was looking into improving this with the meditation focus. And extending this to the player's pawns wouldn't be so hard to do. :-)

> And last, and off topic but I didn't want to make another post, maybe an option to hide or collapse all techs of a specific tech level, if a pawn knows all of them? 
- Have you noticed the "expand" icon on the Tech Tab on our last update? ;-)

**Comment by chrispikula** [comment]
>  Have you noticed the "expand" icon on the Tech Tab on our last update?  ;-)

Very nice!  I like!

> I have considered making that number customizable, but I'm sure people would just abuse this, which would ruin the experience. 

Yeah, I can see that.  It'd have to be really tightly bounded, otherwise people would just 'overfarm' new arrivals / prisoners with prison labour.

> I'm not ruling that out yet, but I'd rather find ways to achieve the same result by other means. One thing I did was making the tech pool from which the initial expertise is sorted for the player's pawns to be configurable. Have you seen that option on the settings panel? If you want to, you can focus them to the faction's starting research instead of their tech level. That wound narrow it down to more useful techs. And you can also include additional starting techs to the scenario, those are also added to the mix.

I've been playing 'New Tribe' with this mod, and attempting a 'random research' type deal.  So, sadly, no starting techs for me!  :-p

**Comment by abrenneke** [comment]
Just for the discussion, this is the "starting research" algorithm that I've replaced the current one with and am using:

```csharp
 // Clear current research
var pawns = Find.World.PlayerPawnsForStoryteller.Where(p => p.IsColonist).ToList();
var researchManager = Find.ResearchManager;
var currentResearch = researchManager.GetPrivate<Dictionary<ResearchProjectDef, float>>("progress");

foreach (var key in currentResearch.Keys.ToList()
    .Where(key => currentResearch[key] > 0))
{
    currentResearch[key] = 0;
}

// Remove starting pawn expertises
foreach (var pawn in pawns)
{
    var knowledge = pawn.GetComp<HumanResources.CompKnowledge>();
    foreach (var tech in knowledge.expertise.Keys.ToList())
    {
        knowledge.expertise.Remove(tech);
    }

    knowledge.proficientWeapons.Clear();
}

// Generate starting research
var startingResearch = DefDatabase<ResearchProjectDef>.AllDefsListForReading
    .Where(def => def.GetModExtension<StartingResearch>() != null).ToList();

var researchCount = new[] { 9, 10, 11, 12, 13, 14 }.RandomElement();

// Give one research to the best pawn for that research, and then also mark
// that research as completed, so it can be used immediately.
// The same research can be given to multiple pawns, will still take one of the research "slots" (researchCount)
for (var i = 0; i < researchCount; i++)
{
    var research = startingResearch.RandomElementByWeight(x => x.GetModExtension<StartingResearch>().weight);
    var researchSkill = research.GetModExtension<StartingResearch>().skill;

    var pawnsBySkill = pawns.OrderByDescending(p => p.skills.GetSkill(researchSkill).Level);
    foreach (var pawn in pawnsBySkill)
    {
        var knowledge = pawn.GetComp<HumanResources.CompKnowledge>();
        if (knowledge.expertise.ContainsKey(research))
            continue;

        GivePawnResearch(knowledge, research);
        break;
    }
}

...

// All types not in this lib need to be boxed in object because of RW type loading stuff, even private
private static void GivePawnResearch(object knowledgeBoxed, ResearchProjectDef research)
{
    var knowledge = (HumanResources.CompKnowledge) knowledgeBoxed;
    if (research.prerequisites?.Count > 0)
    {
        foreach (var prereq in research.prerequisites)
        {
            GivePawnResearch(knowledge, prereq);
        }
    }

    if (knowledge.expertise.ContainsKey(research))
        return;

    knowledge.expertise.Add(research, 1.0f);
    Find.ResearchManager.FinishProject(research);
}
```

This way, the pawns get research that they're most likely to know, and also, all of the research any pawn knows, is part of the "implicitly known" group, so none of the pawns have to document what they already know. I've found this to be pretty fun, and not annoying. Sometimes there's some really important research that none of the pawns know, which can throw a fun twist into things.

**Comment by jptrrs** [comment]
You gotta love hands-on people!
So, you randomize a selection of techs from the starting research group and map them 1:1 to the pawns taking the skill into consideration, then mark that project as finished, is that it? If it's a starting research, you didn't really need to finish it..
Apart from the fixed number of techs to be distributed, is the same effect as choosing "Knowledge generation draws from the starting techs for that faction only" on the mod options menu. :)

**Comment by abrenneke** [comment]
Yeah maybe this could have been a simpler way! Just sharing what works for me! With this setup, the "starting research" is randomized as well.

**Comment by jptrrs** [comment]
I'm glad you shared it! I always like to see new perspectives into some problems I faced myself. :)
Yeah, it's randomized in the sense that your paws start with access to a subset of techs from the starting research. But if I understood it correctly, if you build the study desk you'll still be able to study the remaining ones to fill the gaps, right?
It seems to me the main difference from what the mod already does with that option selected is to guarantee a given number of technologies is handed down to the colonists, instead of relying on my arbitrary number of techs per colonists.

**Comment by abrenneke** [comment]
> if you build the study desk you'll still be able to study the remaining ones to fill the gaps, right?

Yeah totally, but I found it very confusing and frustrating for there to be technology at the start that is _researched_, but that none of the pawns _actually know_. Took me waaaaay too long to see that the study desk "includes all of your faction's starting research". I always start with a neolithic tribe, so I bet my method doesn't work as well for starting later in the game.

**Comment by jptrrs** [comment]
Everybody nowadays rely on transistors and integrated circuits. It is researched. Nevertheless, can you build one? 
That was my thinking.

**Comment by abrenneke** [comment]
Right yeah, that makes sense for industrial factions. Starting at neolithic, it doesn't make too much sense for the table to magically have knowledge on things that the pawns don't know.

**Comment by jptrrs** [comment]
I see where you're coming from.

**Comment by jptrrs** [comment]
With the last changes allowing the pawn's background to affect its knowledge, if the appropriate option is selected on the settings panel, I feel we've covered the last possible suggestions on this issue. So I'm closing it. Thanks!
