### ISSUE TITLE
Incompatibility with Genetic Rim

### ISSUE THREAD

**Issue by MinerSebas** [jptrrs/HumanResources#46]
Mod: https://steamcommunity.com/workshop/filedetails/?id=1113137502

Log: https://gist.github.com/c7e6c7684ebc0ca65fe808be2d6c5820

When trying to show common Weapons on the Weapons Tab, all Weapons disappear in the Window and the Buttons.

Reproduction Steps:
1. Start a Game with any Scenario
2. Open the Tech Tab of any Pawn
2.1. You can disable the display of ranged Weapons, as the bugged weapon appears to be a melee weapon.
3. Click "Show Common Weapons"

Now no Weapon will be displayed, and the Error Log gets filled with error messages.

**Comment by chrispikula** [comment]
I have Genetic Rim, and have a similar issue, but can't confirm that it's *just* Genetic Rim that does this, as I haven't narrowed it down yet.

The issue does persist between dropping to the main menu, and reloading a new save, however, so there's no way to switch back to the 'show all weapons' option: As soon as you open the Tech tab of any pawn, errors start again and any widgets in the tab become unclickable.
