### ISSUE TITLE
Multiple Documentation Bills on the same Workbench Bug [Minor]

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#47]
So, this is a minor QoL bug(s), but it is easily repeatable, but appears as a mod-breaking bug unless you are aware of it and how to work-around it.

If you start a new tribe, with a bunch of pawns, you've got a dozen or so techs that are undocumented that it'd be nice to proliferate.  Due to how I've found I need to get the pawns to work on Documentation, I need to make a separate bill for each and every tech that I want to put in a bookshelf.  

Only the first bill of a type gets checked when a pawn is forced to a Study or Research Desk.  So if Pawn A knows Agriculture, and Pawn B knows Devilstrand, and you have Agriculture Documentation in a Bill, and Devilstrand in a Documentation bill directly after, and then try to force Pawn B to work at that Study desk, they'll do nothing.

Furthermore, if their highest priority task is to study, and they can only do secondary Bills, they'll go into 'Standing' Mode, and do nothing at all, even if there are lower priority jobs available as well.

This type of behavior can also be shown at the research bench, by making it so that only a single pawn can work on a bill.  (Say, if you don't want every pawn to work 5% on a really hard tech.)  Any secondary research options after that will also not get attempted.

Another way this shows up, is that if you have a bill that's set to run two times, and you want to Document both Devilstrand and Agriculture in it, and the two pawns, A and B, don't know the other tech.  I believe that one of the pawns will be unable to document, (or Research, as the case may be with pre-req techs), as the iterator going through the list to check to see if the pawn can work at that bench sees the pawn can't do the tech that it finds first (even though it can do the second), and then stops, leading the pawn to not work at the bench.  Note:  Both pawns usually have the option to 'Force' to do work, but one of them won't even take a step towards the bench.

I do have to wonder, a bit, why there isn't a type of 'Document Everything You Know' bill?  One that checks the Pawns knowledge for completely discovered undocumented techs, rather than the player having to choose which techs to document?  I mean, I get that it'd make the game a bit easier, what with less of a need to micro all of your bills, but it's only an issue either way in the first quadrum or so, after that, you've got one, maybe two pawns dedicated to research and it's not really noticeable anymore?

I say it's minor, but I feel bad, a little bit, as it's likely not going to be a straight-forward fix.  :-(

*NOTE:  I just realized that I may be exacerbating the issue somewhat with 'No Job Authors', a mod that lets any pawn continue work on unfinished things.  So a tech book that's unfinished by pawn A can be picked up by pawn B, if both know the same tech.  It's an issue that only shows up at the start, in the first quadrum, but it may be a *slight* part of it, for the one or two techs that multiple pawns may know at the start.

**Comment by jptrrs** [comment]
Now that's a helpful investigation! It seems you figured out where the bug
is hiding. Thanks! I'll look into it when I get the chance. :-)

Em ter, 30 de jun de 2020 12:36, chrispikula <notifications@github.com>
escreveu:

**Comment by jptrrs** [comment]
Fixed! That was a good one!
