### ISSUE TITLE
Incompatibility with Simple Search Bar [minor, non-interaction]

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#48]
Simple Search Bar adds a search bar to help filter bill ingredient lists and stockpile options.

Straight up, does nothing with this mod's bills.  :-D  It shows up, but no filtering occurs if you type into it.

It also may be a source of the lag that occurs when I try to select a tech, if it's firing it the background all the time, but that may also be because of my 800 techs.  :-p

**Comment by jptrrs** [comment]
For the time being, [Rimworld Search Agency](https://steamcommunity.com/sharedfiles/filedetails/?id=726479594) does the same and it works natively with HR.

**Comment by jptrrs** [comment]
Considering we got rid of the bills altogether, I believe this issue is kaput.
