### ISSUE TITLE
Add a way to see tech-prerequisites.

### ISSUE THREAD

**Issue by jptrrs** [jptrrs/HumanResources#49]
Jernfalk:
Hey man, awesome mod, using it a lot. But please, add a way to see tech-prerequisites (since later techs need an installed Multi-analyser to see the path, which doesn't exist) or maybe make the mod auto-queue the necessary research for the selected item.

**Comment by Exidoous** [comment]
Research Pal shows prerequisites, but both Tree and Pal use the lock graphic for those technologies whose major prerequisite is not (vanilla) researched. 

Nothing is (vanilla) researched with this mod, so we always see those locks, which block the prerequisite display functionality.

**Comment by jptrrs** [comment]
Thanks for the info, Exidoous. If the prerequisites are shown (as in highlited) with ResearchPal, then that is something with Research Tree itself. 
But you can do research with this mod, even though the pathway is different. The locks should go away when you build the appropriate required building (the hi-tech research bench and then the multi-analiser).

**Comment by jptrrs** [comment]
I believe the last changes solved this issue.
