### ISSUE TITLE
Medical InferSkillBias

### ISSUE THREAD

**Issue by mrsebseb** [jptrrs/HumanResources#5]
Error with **VGP Garden Medicine** and ### WarCrimes Expanded 2 stem from a NRE
in _InferSkillBias_.
This is because _r.workSkill.label.ToLower()_ returns **_medical_** and attempts to set **_medicalTag_** 
which does not exist, rather than setting **_medicineTag_**

**Comment by jptrrs** [comment]
Fixed on 0.6.1
