### ISSUE TITLE
Idle Manual Priorities

### ISSUE THREAD

**Issue by Exidoous** [jptrrs/HumanResources#53]
When assigning Learn to a higher priority (with vanilla Manual Priorities) pawns will idle, rather than doing their lower-priority jobs, whenever a Learn task is not available.

**Comment by jptrrs** [comment]
Ok. This could indicate a silent error. Can you send me your Ctrl+F12 log?

**Comment by Exidoous** [comment]
EDIT:

Fixed in .15 :D
