### ISSUE TITLE
Prison Labor Incompatibility - Prisoners Learning Techs from Books

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#54]
So, I've found a _slight_ incompatibility with Prisoner Labor.

While it is completely possible to make prisoners in the Prison Labor mod document techs that they already know, there is no way to make them learn techs from books in linked bookshelves.  Or any at all, really (ie, the ones you get even if you start as a 'New Tribe').

Save-file editing so that the prisoner gets the appropriate tech (Stonecutting, in this case), lets them use the workbench that they weren't able to use before. (Rock Mill from Fertile Fields, and Electric Stonecutters Bench from Vanilla Furniture Expanded - Production, both with 'Make any Stone Blocks')

Steps taken to isolate issue:  Prison Labor, all labors enabled, all schedule set to anything for prisoners, full motivation and near full mood.  Workbenches set up with and without prisoner-only bills, both within and outside of prison-only labor area zones.  All workbenches had a book shelf linked, and prisoners failed to work with any bench to learn techs when specified tech book was in or out of book shelf.  No errors, red, showed up.  I believe no yellow error showed up in the console, but I closed my game at the point where I'm typing this out, so I can't be certain  Nothing showed up in the post-game log file, at any rate, other than one colonist getting a hell of a lot of 10 jobs in one-tick followed up by 10 'tried to learn a null project', but that's probably due to the tests that I was running, and the prisoner-only workbench and zone authorization.

I've noticed that prisoners can't research technologies either, but this seems less important, as you wouldn't want them to do so.  I did the same tests for this, btw.  Also, with Intellectual scores in the 0's and 1's, it'd take a hella long while anyways.

Fun note:  You can set bills to create a second tech book, which I will make use of in the future for 'job class-specific training rooms.  All you need to do is drop the specific tech from a bookshelf and keep it un-allowed, and you can document it a second time.  Good stuff.  (The reason for the rooms and duplicate books:  Everybody needs Electricity, but not everybody needs to know the GeneticRim Tech's.)

Minor note:  It takes quite a bit of micro to put a specific book in a specific book shelf.  Fasted I've found is to eject/drop the book from the book shelf, allow it, force a pawn to pick it up, draft them, move to the new book shelf, drop the book, undraft, and force them to haul it.

**Comment by jptrrs** [comment]
Ok, I can confirm the issue. I'm happy any task is working at all, since I haven't really designed it with prisioners in mind! I'm going to look into it.
About the trouble you're having selecting specific books for each shelf, you could simply select what you want on their "storage" tab. Much easier ;-)

**Comment by jptrrs** [comment]
Love it when its easy! Fixed for the next update.

**Comment by chrispikula** [comment]
Yay! :-D
