### ISSUE TITLE
With the Z-Levels mod, Colonists won't research on their own anymore

### ISSUE THREAD

**Issue by Torebun** [jptrrs/HumanResources#55]
The Error:
Colonists never execute the study job on their own. It has to be constantly manually forced to make them do research with both the Zlevels and HR mods active together.

Modlist was trimmed down to just Harmony/core/Hugslib/ResearchTree/HumanResourses/ZLevels. I tried different order of the last three mods but the issue never resolved.
In order to trim down 150 mods to these two, I kept generating a new world and new map and turning on god mode with dev to drop a research bench with a bill with technology assigned to it to see if any colonists would research at the bench. The mods were never loaded mid-save.

HugsLog: https://gist.github.com/HugsLibRecordKeeper/56cad93821d1fab793fe2615ff21628e

Forcing a colonist will make them actually study as intended, but they'll never do it on their own and will eventually stop after a short time making it sadly unplayable.

Z-levels mod link as asked: https://steamcommunity.com/sharedfiles/filedetails/?id=2127428910
But I will CC to the Z-levels mod author as well.

**Comment by chrispikula** [comment]
What priority were the Study and Research jobs at for pawns?

**Comment by Torebun** [comment]
> What priority were the Study and Research jobs at for pawns?

They were at 1. I tried to remove all other tasks but they would just wander instead.

**Comment by jptrrs** [comment]
Thanks for reporting, Torebun. But the link for the log is missing...

**Comment by Torebun** [comment]
Updated it, github formatting didn't turn it into a link so it's just plaintext now. (apparently it linked up automatically as plain, cool)

**Comment by jptrrs** [comment]
I just tested and it seems to work now. Since Z-levels is still in development, I assume they fixed it on their end.
