### ISSUE TITLE
Unable to apply techprints

### ISSUE THREAD

**Issue by Americangrit1** [jptrrs/HumanResources#57]
So I saw this in my actual play through and, just to make sure it wasn't a mod compatibility, ran a clean game with just the mod, research tree, and hugslib. I made sure the pawn I was using had learned all of the pre-req techs, but I tested about half of the techprints and was unable to apply any techprints to start researching techs which require tech prints. The game did not kick anything over to the error log, only gave the error "cannot apply: No un-reachable, un-reserved research bench available." 

Just for sanity check, here are my logs:
https://gist.github.com/HugsLibRecordKeeper/1e1e1be944869379b0abe77f59829911

**Comment by jptrrs** [comment]
So, you're trying to research technologies that have other technologies as
pre-requisites, is that right?
Are those pre-requisites discovered? Unless they are starting technologies
for your faction/scenario, that means they must be stored on any bookshelf.

João Pedro

**Comment by mrsebseb** [comment]
With the Royalty DLC (and some mods dependent on it) some research requires that  you "unlock" the research option before it can be researched by using an item called a [Techprint](https://rimworldwiki.com/wiki/Techprint)

With this mod, TechPrints can't be used.

**Comment by jptrrs** [comment]
Oh, I see. Thanks for reporting, I'll take a look.

João Pedro

**Comment by jptrrs** [comment]
Fixed!
