### ISSUE TITLE
[Suggestion] Pawn can train another pawn in a weapon proficiency

### ISSUE THREAD

**Issue by warrook** [jptrrs/HumanResources#59]
Just so that I don't have to send all of my pawns through the entire tech tree to be able to wield a charge rifle (for example).

**Comment by jptrrs** [comment]
But you don't! https://github.com/jptrrs/HumanResources/wiki/Getting-Started#5-weapon-proficiency-doesnt-depend-on-technology-expertise-so-prepare-your-training-program
