### ISSUE TITLE
Pawns sometimes(?) do Document Technology before Study Technology, ignoring task order

### ISSUE THREAD

**Issue by Exidoous** [jptrrs/HumanResources#61]
Scenario: There is one Study Desk. Top task Study Technology assigned to particular pawn (with available, prerequisites met, unknown-by-pawn technology selected). Second task Document Technology assigned to all pawns (particular pawn knows an unrecorded technology). The particular pawn will Document Technology first, seemingly ignoring the task order in the bench's queue.

The technologies at issue in my example, if relevant, are Document (Natural Internal Organs, from Questionable Ethics Advanced) and Study (Electricity).

I can override the default by ordering the particular pawn to study or document, without issue, but commanded tasks don't last long, and the pawn quickly reverts to the behavior described above.

**Comment by jptrrs** [comment]
Hi! Yeah, it seems counter-intuitve, but the bill order on the bench doesn't matter when the tasks are different. Your pawn is following the basic priority we defined (on request, by the way): document first, then study. As far as I know, this is a quirk from Rimwolrd's work system, and I'm not sure we'll be able to change that. You could use [Wor Tab](https://steamcommunity.com/sharedfiles/filedetails/?id=725219116&searchtext=work+tab) to set different priorities within the study work type.
