### ISSUE TITLE
Training Unresearched Weapons

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#63]
Hi again.  :-D

So, would it be possible, at, say, a 5 or 10x penalty or so, to be able to have a pawn train in a weapon that does not have the associated tech researched yet?  

I've just had a raid come in with a donation, and all I can currently do is put the weapons they brought in storage.  Can't even pull the trigger, or swing the special sword.  :-p

Fun side note, too:
If you accidentally have all weapons selected in the training bill when you try to force a pawn to work at a shooting target, the game freezes for a solid 5 minutes or so.  Oof.

**Comment by jptrrs** [comment]
I believe that would defeat the mod's purpose, so the answer is no. But I'll think about it.
About the the freeze, error log!
