### ISSUE TITLE
Pawns are trying to learn Null Projects

### ISSUE THREAD

**Issue by JukeDragh** [jptrrs/HumanResources#65]
My pawns often stand around when they are near the bottom of their priority list when they should be researching. Looking in the logs revealed these lines:

> [Human Resources] Jay tried to learn a null project.
Jay started 10 jobs in one tick (A list of 10 Human Resources LearnTech jobs, all with the same id)

These fill the log for as long as they are standing.

HugsLib F12 Log
https://gist.github.com/2f82c764b0f9b57f302d6edb89709af3

Other info: 

- I have a very big mod list, however, none of the techs that are hanging are modded. It isn't unlikely there is a research related mod that might be causing an incompatibility.

- I have three researchers, each with their own bench. ATM, only two of the researchers bug out like this, but the other one used 
to.

- You can actually get them to do the research they are hitching on by prioritizing it manually.

**Comment by JukeDragh** [comment]
Might have found the thing causing the issue. While investigating why only two of the researchers had this problem, I found a common thread: the researcher without the problem had her Study Tech bill suspended. Sure enough, after suspending the Study bills of the other two, the problem seems to have stopped. 
All of my researchers had finished all the Technologies that I had given them on the Study bill so that might pertain to it.?

**Comment by jptrrs** [comment]
Hi Juke! Thanks for investigating this. Yeah, that suspended job might be causing the issue, even though it shouldn't. I'm about to overhaul the job system entirely, I'll make sure to test this specific use case so it doesn't happen anymore. Thank you very much!

**Comment by JukeDragh** [comment]
Cool, I got the everything you need to replicate it:

- Harmony, Core, Royalty, Hugslib, Human Resources, ResearchPal
- Spawn or Construct a Study Bench
- Add a Study Technology bill to the Study Bench
- Set the bill to 'Do forever'
- Allow technologies.
- Have a researcher know all the allowed technologies at this Study Desk.

If all these happen, whenever the pawn that knows everything from that Study Desk tries to use it, they will hitch and try to learn Null which puts them into a loop. 

HugsLib log from the debug world I used:
https://gist.github.com/7dd28202de1f7e506b3c653ad3ccfc76

If you need the save for the debug world, just ask.

**Comment by jptrrs** [comment]
That's awesome! You just saved me a lot of time.

**Comment by jptrrs** [comment]
I believe the last changes solved this issue. Comment back if I'm wrong!
