### ISSUE TITLE
Fast Study, with no tech chosen, repeated forever

### ISSUE THREAD

**Issue by chrispikula** [jptrrs/HumanResources#66]
Hello again!
So I recently befriended a pawn who crash landed in my base.  Fair enough.  He had a couple modern techs that I didn't have, but I didn't bother documenting them as his intellectual score was too low at the time.

So I set him to study everything, to boost that up.  It worked for the rest of my pawns, who were all from tribal level backgrounds.

After an hour I noticed that whenever he was studying, he got stuck repeating an empty, no error causing study job over and over.  

It turns out, that if you have a job that says study everything, as opposed to just, say, neolithic and medieval, that the pawn won't learn any of the basic techs at all, except for when you force them to a desk.  When they continue at that desk for the second research, or when they decided to study on their own, they'll study nothing, with a quickly filling progress (5-ish seconds) bar over and over.

As you surmised, changing the study techs to just the first two tech ages stopped the repeating issue.

I think it has to do with a pawn trying to study a tech that's a pre-req of one of the ones they know, but that you don't actually have researched yet.  I could be wrong.

**Comment by jptrrs** [comment]
Hi, thanks for reporting it.
I'm currently working on a revamped method to assign research and study which in theory should prevent this sort of thing. But in the meantime, if you can send me you log it would be useful, with or without an apparend error. Thanks!

**Comment by abrenneke** [comment]
@jptrrs I'm on the latest master and it's still happening - when I had Study above Document, this happened. When I moved Document above Study, the pawn started documenting as normal!

**Comment by jptrrs** [comment]
Hmmmm.... Weird.
The OP mentioned selecting everything for him to study, which ment having all techs selected on the bill. Since there's no tech selections at the bill level anymore, can you detail what you did to get to that state? Also, please hit Ctrl+F12 and send me your log! Can't do anything without it.

**Comment by abrenneke** [comment]
I'll check next time I run the game @jptrrs! Could the document and study bills be simply removed with the new researching system? (which is fantastic btw)

**Comment by jptrrs** [comment]
Hmmmm.... maybe. I haven't thought of that. I feel the bills are a good way of controlling who does what and when. But maybe that's just my play style speaking. Also, it's very convenient to simlpe adhere to the task framework the game already uses. The document job is just a glorified make thing task, for instance. That would require some re-work of the workGivers....
It's something to consider.

**Comment by jptrrs** [comment]
I'll keep that thought, but I'm closing the issue, since I solved bill ordering on the last update, v.018.
