### ISSUE TITLE
Mod Conflict: Android Tiers

### ISSUE THREAD

**Issue by vlad1492** [jptrrs/HumanResources#7]
When adding androids, there is no 'Tech' tab for the Android pawns. 
Pawns cannot right click to build the study desk. They will build it as a regular task. 
Regular pawns can use the study desk, androids cannot.

Adding just the prerequisite mod, Humanoid Alien Races 2.0, doesn't seem to do this. 
Human pawns appear to have a tab and are able to build and use the bench. 

Humanoid Alien Races 2.0
https://steamcommunity.com/sharedfiles/filedetails/?id=839005762

Android Tiers
https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863

Log:
https://gist.github.com/263fc0900c6bc8739d78f97b6ca4b86d

**Comment by jptrrs** [comment]
Thanks for reporting, vlad. 
We just corrected the issue with right-clicking. But those with non-human pawns will require some investigation.

**Comment by vlad1492** [comment]
I'm sure it would be appreciated. I just started fiddling with androids but I know there are a bunch of other popular non-human mods out there.

**Comment by jptrrs** [comment]
I modified the action restrictions so they don't affect hon-human pawns anymore. Please, check if the androids issue is fixed for you on version 0.8.

**Comment by vlad1492** [comment]
Added Android Tiers back in to my current mix, same result. No tech tab, unable to interact with study desk by right clicking. 
https://gist.github.com/448d2de85ba0b2c1cb964835b9b8eded

Also tested with stripped modlist, same result. 
https://gist.github.com/099e82582f3ca81e5fdfc8214bb956a9

**Comment by vlad1492** [comment]
Actually it seems no right clicking on *anything* now.  Remove HR, retry - business as usual.

**Comment by jptrrs** [comment]
Ok, so it needed some deeper protections against weird kinds of pawns, like the androids. Fixed on the next update.
