### ISSUE TITLE
Documentation Fixes 

### ISSUE THREAD

**Issue by Shuro** [jptrrs/HumanResources#72]
Hi,

here is a minor bug report for your github wiki:

In example on the mod compability wiki page are some URLs wrong, in example:
`* [Research Tree](steamcommunity.com/sharedfiles/filedetails/1266570759)`
instead of
`* [Research Tree](https://steamcommunity.com/sharedfiles/filedetails/1266570759)`

which causes it to link like 
`github.com/jptrrs/HumanResources/blob/master/steamcommunity.com/sharedfiles/filedetails/1266570759`

I would have made a pull request, but forking a repo doesn't seem to fork the wiki.

Best regards,
Shuro

**Comment by jptrrs** [comment]
Thanks for reporting this. It's fixed now. Thanks!
