### ISSUE TITLE
(Different) Error with simple sidearms

### ISSUE THREAD

**Issue by RavenclawMuggle** [jptrrs/HumanResources#73]
If a colonist is using simple sidearms, and they go to learn a new weapon, it causes them to forget about whatever sidearm they had been set to keep.

**Comment by jptrrs** [comment]
Please, check if it's still present on the latest update, version 0.16. Thanks.

**Comment by ELLIOTTCABLE** [comment]
This still seems to be an issue in v0.16 — if my pawn has weapon A equipped, and weapon B set as a sidearm; then instructing them to learn weapon C causes them to forget entirely about weapon A.

To be clear, I'm not so sure this is an issue that's specific to Simple Sidearms, so much as it's more *visible* when using Simple Sidearms. Without SS, you'd still "lose" weapon A, and have to go hunt it down in a stockpile where it got hauled, manually re-equipping it to your pawn after they were done training … however, with Simple Sidearms, this becomes orders of magnitude *more annoying*, despite not being any different. Demonstratum:

1. Have pawn with A equipped, B as a sidearm, and C and D as tools. Pawn goes to train X. Picks up X, dropping A.
2. When training X is completed, pawn drops X; now, B is their 'primary weapon.' They continue their training bill, heading to train weapon Y. Picks up Y, dropping B.
3. Rinse, wash, and repeat; "losing" one sidearm for every new weapon they train.

This becomes super-annoying if you have 𝑛 pawns with 𝑥 weapons/sidearms/tools each, presumably specific to those pawns; any time you "turn on" your training bills, once everybody's done training up on the new weapons, you're gonna have to go through your pawns by hand, manually re-equipping and re-sidearm'ing 𝑛×𝑥 items!

Suggestion: If SS is *not* installed, pawns should hold on to their existing weapon when picking up one to train, keeping it in their inventory; then, when completing training, they should switch back to it from their inventory. If SS *is* installed, then ditto, but mark the swapped-away-from weapon as a 'missing sidearm' as well, so they'll hunt it down if it gets dropped or lost, or the training gets interrupted.

**Comment by jptrrs** [comment]
> Suggestion: If SS is _not_ installed, pawns should hold on to their existing weapon when picking up one to train, keeping it in their inventory; then, when completing training, they should switch back to it from their inventory.

I managed to implement that, except it will be that way regardless of SS being installed or not. On my tests with SS, pawns forget the temporary weapon as soon as they re-equip the original one. But since that mod is full of options, we'll have to wait and see what happens.
