### ISSUE TITLE
Visitors / guests from the "Hospitality" mod, probably shouldn't be able to study

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/HumanResources#77]
I like to have a few 'any colonist' jobs on my HR buildings - train fire-extinguisher, automatically, for every new pawn; learn basic construction techs like Electricity and Smithing, etc.

I just glanced over and see that Hospitality guests have grabbed fire-etinguishers, and are "training" at my target stand. I don't really feel like donating my technology and knowledge to visitors. 👍 

Obviously not a pressing issue, just a might-be-nice.

**Comment by jptrrs** [comment]
First, the image of someone pissed off when a visitor decides to empty a fire extinguisher at the target range is hilarious!! Such disrespectful guests! =D
But that's a tricky thing... I believe Hospitality enables guests to do chores at your colony by default. It would take coding a very intrusive and specific counter-measure... Maybe it would be easier to set your training range as an off-limits area for your guests?

**Comment by ELLIOTTCABLE** [comment]
Really good idea re: the workaround, didn't even think of that!

Leave it on the back-burner, IMO, and see if anybody else complains. ¯\_(ツ)_/¯

**Comment by jptrrs** [comment]
Fixed on version 0.30.
