### ISSUE TITLE
Pawns unable to write books after update.  Yellow progress bar just fills and restarts.

### ISSUE THREAD

**Issue by steinbajl** [jptrrs/HumanResources#79]
Not sure if I am doing this right.  I removed all mods except the ones you listed and it worked fine.  it must be a conflict so I will start adding mods a few at a time.  i do not know what an error log is but if it is the long list when the game starts with the white, yellow, and red messages, I think I uploaded that file.  not sure.    https://gist.github.com/HugsLibRecordKeeper/22e7e8b52e1eab6dc6ba90274502b363#file-output_log-txt

https://gist.github.com/22e7e8b52e1eab6dc6ba90274502b363

hope one of these works.

One of the errors lists in yellow is:

[Human Resources]  No relevant skills could be calculated for VWE_SpecializedFirearms.  It won't be known by anyone.

Another thing I notice is I now get a warning message on the right side of the screen that says I do not have a research project selected, even though I do and someone is researching.  Not sure if that is part of the same issue, but wanted to mention it.

Hope this helps.  I will start sorting my thousands of mods....

**Comment by steinbajl** [comment]
Update:   I was able to correct the problem by only listing one bill per study bench.  If the study tech bill was listed first they would study but not write the books.  If the write tech bill was listed first they would write the book, but not study.  By using multiple desks with only one bill for each I was able to make the game work!

**Comment by jptrrs** [comment]
That was the crucial piece of information. I was able to reproduce what you're seeing. Thanks for reporting I'll definetely look into it!

**Comment by jptrrs** [comment]
I believe that was actually an old error that before the update was simply too hard to reproduce. Anyway, once you pinpointed the conditions for it to happen, I was able to chase it down. It was actually an easy fix. Mod is updated, please check it.
