### ISSUE TITLE
Starting weapons include monosword, plasmasword, zeushammer

### ISSUE THREAD

**Issue by vlad1492** [jptrrs/HumanResources#8]
Maybe this is deliberate, these seem pretty hi-tech. 
https://gist.github.com/263fc0900c6bc8739d78f97b6ca4b86d

**Comment by jptrrs** [comment]
Are those starting weapons for all pawns? Do you mind pointing out from which mod those came out?

**Comment by vlad1492** [comment]
All pawns, yes. 
Pretty sure it comes from Royalty, will need to test with a stripped modlist.

**Comment by vlad1492** [comment]
Confirmed, they show up on a stripped modlist too.

**Comment by jptrrs** [comment]
Ok, Thanks!
