### ISSUE TITLE
InvalidCastException when loading saved game

### ISSUE THREAD

**Issue by abrenneke** [jptrrs/HumanResources#80]
Since updating to the new version, I've been getting this error once when I load saved games, not sure what's causing it, haven't looked into it:

```
[HugsLib][ERR] JPT_HumanResources caused an exception during OnMapLoaded: System.InvalidCastException: Specified cast is not valid.
  at HumanResources.ModBaseHumanResources.MapLoaded (Verse.Map map) [0x00038] in <16471bfa328e4832a5bc4535110c976a>:0 
  at HugsLib.HugsLibController.OnMapLoaded (Verse.Map map) [0x00021] in <e4b32d84f714481f906e5eea5e560e3b>:0 
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
HugsLib.Utils.ModLogger:ReportException(Exception, String, Boolean, String)
HugsLib.HugsLibController:OnMapLoaded(Map)
HugsLib.<>c__DisplayClass76_0:<OnMapInitFinalized>b__0()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
```

Method:

https://github.com/jptrrs/HumanResources/blob/0ffad51ba8bf91edbc9672dfeff0a4fd547f51b9/Source/Base/ModBaseHumanResources.cs#L158-L177

On a quick glance, I think it might have something to do with the [Gloomy Vanilla Overhaul](https://steamcommunity.com/sharedfiles/filedetails/?id=1883678698) mod replacing the research bench? Just a guess.

**Comment by jptrrs** [comment]
Would you mind sending me an old savefile where it occurs?

**Comment by abrenneke** [comment]
Here's the save, I kind of doubt you'll be able to load it though 😆, but maybe

[The Notorious Staff Union.zip](https://github.com/jptrrs/HumanResources/files/5396915/The.Notorious.Staff.Union.zip)

**Comment by jptrrs** [comment]
Don't really need to load it to know. ;-) 
That file was not saved with an old version of HR. It seems it's from after the fact. That's becasue the mod is listed as active, but the research benches classes are unmodified. That method only kicks in when it finds research benches modified by older versions of HR, which used to switch their classes.

**Comment by abrenneke** [comment]
well, that error and stack trace are for that save 😉

**Comment by jptrrs** [comment]
Really? 
I'm wondering if Rimworld updated the mod list behind the scenes... Anyway, I did some testing and ended up stumbling on the same error when loading a vanilla save. I'm looking for a solution.

**Comment by jptrrs** [comment]
Re-wrote that method to trigger without casting anything. It should be fixed on the next update. Thanks for pointing it out!
