### ISSUE TITLE
[Feature Request] Alternative, more balanced way to access late-game weapons, without learning how to *literally* make them

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/HumanResources#82]
So, I'm *really* enjoying my Human Resources playthroughs - I think you've come up with something really great here, that belongs in the core game. A great balance of "fun" micromanagement that doesn't become grueling (or at least, won't, as you polish up some of the rough edges on the beta!)

That said, I *really believe* the "no weapon use whatsoever until you learn how to literally build the thing" is not just unrealistic, but really unbalanced in the game overall as it stands. Note, for reference:

- Traders are designed to come by, occasionally selling really advanced or powerful weapons that otherwise wouldn't be available to you yet;
- You can still buy/use/plan around advanced *armors* as early in the game as you can afford them (which if anything, would be more complicated to use effectively than simply 'pick up, point, pull trigger' of most weapons); and
- In the base game, there's an *entire scenario*, one of only three, where you start the game with a single Charge Rifle; and that weapon becomes beloved to you throughout the entire playthrough, being passed from best-shooting-colonist to best-shooting-colonist until it's durability 5% and doomed to sit in a stockpile forever. (I think it's worth noting that you had to *special case* that scenario: maybe that's indicating that there's something wonky with the core mechanic you're patching!)

so, all this said, I posit that getting ahold of one, or two, advanced / "unbalanced" weapons early on in a playthrough is totally a reasonable thing that can contribute to the fun of a playthrough without overall unbalancing the game. In fact, I think it's something the game is *designed* around, and playing with Human Resources right now actively makes the early/midgame substantially more difficult, as those will *never* be available!

----

Okay, all that said, I propose an alternative solution, that I think you might really like / that I think really falls "in line" with the goals of HR:

**Weapon experimentation.**

Allow a pawn with high shooting *and* intellectual skills (take the average, as [Mortar Accuracy](https://steamcommunity.com/sharedfiles/filedetails/?id=1729446857&searchtext=mortar+accuracy) does; this requires you to probably step a researching-pawn away from research, losing a bit of opportunity-cost … but also ensures that the pawn who does this won't be *totally* useless with the weapon once they get into combat) to "experiment" with an entirely-unknown weapon. This, like original-research vs. studying already operates, takes way longer than simply studying an existing skill/weapon. After enough experimentation, that unknown-weapon is added to the experimenting-pawn's weapon-list, and can be used — but *only* by them.

Unlike researching, this is not a deep and theoretical understanding of the mechanisms of the weapon — it can't be used to manufacture new ones, nor can it be taught to other pawns — but rather a practical, pragmatic "minimum viable mechanics" to use the dang thing.

I suspect the above would be very easy to implement (new job at practice-target buildings, takes average of shooting/intellectual, takes 10x the time of weapon-practice, adds weapon to the user's weapon-list when complete); but there's one final mechanic I think would add to the fun/danger/tradeoff calculations, if you feel up to the implementation efforts: misfires. Have a small chance of the weapon being experimented with being, uh, catastrophically misused, possibly damaging the weapon, injuring the pawn, or something similar. (Note that What The Hack actually implements this already, maybe [crib off their `ShootRandomDirection()`](https://github.com/rheirman/WhatTheHack/blob/2d1132588f1e8db12f559078ccca19dac2da2ac1/Source/WhatTheHack/Recipes/RecipeUtility.cs#L123-L144)?)

----

Finally, and a bit of an aside: sadly, it'd probably be *more* work than the above, and a lot less fun tbh — but the mod probably really badly needs an options-UI to disable/enable certain weapons from needing training at all. Not every eventually-craftable weapon should be locked behind the relevant technology, or indeed should be practice-with-able at all (I'm looking at you, the single-use Charge Rocket Launcher from [Vanilla Weapons Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360&searchtext=weapons+expanded), or any of the 'ultratech' weapons from [Vanilla Weapons Expanded - Laser](https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844&searchtext=weapons+expanded) that are locked behind almost 20,000 research points, but that can be bought from vendors throughout the game.) It'd be nice to have that configurable per-weapon. ¯\\_(ツ)\_/¯

Hope this was all useful feedback and/or a good idea; if I weren't a macOS user, I'd take a shot at implementing the changes myself!

**Comment by jptrrs** [comment]
Hey, that's the best suggestion anyone gave me so far on the matter! Definitely a great idea. And it comes at the right moment, as I'm currently working on changes to the weapon learning mechanic. This will go well with what I'm cooking up. Good thinking!
About a UI option to free certain weapons from training, that's also not a bad idea. But it is a little harder. What we can do more easily is to find a formula to create exemptions for certain types of weapons. The trick is to find a common denominator, so I don't need to maintain a per-mod list. For the VWE Charge Rocket I found something that connects it to other exempted weapons: it is marked as SingleUseWeapon. That's something I can work with!

**Comment by ELLIOTTCABLE** [comment]
Sounds good; and the above-mentioned "experiment" mechanic solves my concerns with the ultratech-tier weapons that are pretty much designed to be unresearchable. Perf.

**Comment by jptrrs** [comment]
Experiment weapons mechanic is working! Will be up on the next update.
