### ISSUE TITLE
Research Tab Performance

### ISSUE THREAD

**Issue by abrenneke** [jptrrs/HumanResources#83]
Hey again! I'm investigating the performance of my heavily-modded game, and ran a test while the research page is open:

![image](https://user-images.githubusercontent.com/342540/96359414-8c1a4400-10c7-11eb-8907-8d86e80116ce.png)

Looks like Human Resources adds a significant load to ResearchPal. It's likely worsened by the sheer number of mods adding all kinds of things, so anything that loops through all available defs will get significantly longer. I don't believe I have any pawns researching or studying anything at this time.

Here's the profile, in case you have DotTrace: 

[research-page.zip](https://github.com/jptrrs/HumanResources/files/5397091/research-page.zip)

One strange thing has also been going on with my game, and I'm not sure if it's Human Resources related or something else (it takes 2 hours to launch the game with the profiler, I don't like to do it much 😆). When I first go into the research menu, it's _unplayably laggy_. _However_, if I activate the God Mode dev tool, and go into the research tab, it's alright! Then, if I disable God Mode, it's still alright! No clue what would cause that, but it fixes the incredible lag. I'll try to get a profile of that next time I run the profiler.

**Comment by jptrrs** [comment]
Yeah, it does add! After all, there's much to do! Only solution here is not
using HR ;-)
About that God Mode business, it looks like a hiccup on a key ResearchPal
function that is waived when using God Mode. Have you tried using Research
Tree instead? It's the original one, and its code was optimized after
Research Pal branched. It's still on 1.1, but it still works perfectly. And
it gives you a better loading time by shifting the research tree building
step to the moment you actually open it.

João Pedro

**Comment by abrenneke** [comment]
I'll try using tree

**Comment by abrenneke** [comment]
@jptrrs for example, does `get_currentPawns` really need to be called _every frame_? Once when opening the research tab might be good enough? If a pawn dies when you're in the research tab... is it that big of a deal if they stay around until you close the tab? There might be other things to worry about, just thinking out loud.

**Comment by jptrrs** [comment]
Mmm.... yup, we can optimize that. Good stuff!
Up with the next update.
