### ISSUE TITLE
Option somewhere to "research & document"?

### ISSUE THREAD

**Issue by abrenneke** [jptrrs/HumanResources#84]
I'll often mark a pawn to research something, and then completely forget to mark it for documenting once they're finished. On one hand, feels like it takes the difficulty/risk away a bit, but on the other hand, it's annoying to have to manually mark something every single time, since I'll pretty much always want something researched to be documented.

**Comment by ELLIOTTCABLE** [comment]
This is how it effectively worked before the recent refactor — you'd just keep a "document everything" bill open for a pawn, and make sure it's priority was higher than researching in WorkTab; then they'd always go document something if at all possible.

**Comment by jptrrs** [comment]
When you think about it, there isn't really a reason to require the player to assign some tech for documentation when the pawn was already tasked to research it. You guys are absolutely right. It took some tweaking, but I managed to make the research assignment work like that. It will be up with the next update.

**Comment by abrenneke** [comment]
Awesome @jptrrs!
