### ISSUE TITLE
Book shelves full - pawns keep making books

### ISSUE THREAD

**Issue by abrenneke** [jptrrs/HumanResources#85]
Note that I don't know if this is still happening or not!

When all my book shelves were full and a pawn was set to document something, they would write a book....and then write another one, and another one, and another one, until a new bookshelf was made. And then there wasn't a way to delete the extra books without dev mode commands. Either the pawn shouldn't document unless there's space, or a book of the same type stored somewhere should prevent the pawn documenting!

**Comment by jptrrs** [comment]
Yup, that's a problem!

**Comment by jptrrs** [comment]
Found a solution for that. On next update, they won't document if there's no space to store the book.
