### ISSUE TITLE
Vanilla techprints seem broken with v0.16?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/HumanResources#87]
As far as I can tell, post-update, I was able to research *every* supposedly-techprint-locked tech in the game immediately after the update.

Additionally, any techprint items in my colony were unusable, with a message along the lines of 'no available research bench' when right-clicked on. 🤣

**Comment by jptrrs** [comment]
Techprints are unreasonable hard to test, which makes developing code to deal with them a very annoying task. There already are pending issues with them, but thanks for reminding me. I'll look into it when I can, but it might take a while.

**Comment by jptrrs** [comment]
Bingo! Fixed for the next update.
