### ISSUE TITLE
Compatibility issue with Children, school and learning on 0.16

### ISSUE THREAD

**Issue by Thieffi** [jptrrs/HumanResources#88]
Tested with just the base game + DLC with the mods required by HumanResources, and Children, school and learning mod. While 0.16 and the Steam workshop version gives me the error, I don't get the error on 0.15.1

The debug log pops up when starting the game but I can start a new colony so I don't know without playing for longer how big of an issue it is. The error in question is below, the full log is here: [https://gist.github.com/HugsLibRecordKeeper/ea905371341a66416ab8562ca075f81d](https://gist.github.com/HugsLibRecordKeeper/ea905371341a66416ab8562ca075f81d)

```
Failed to find Verse.WorkTypeDef named HR_Learn. There are 22 defs of this type loaded.
Verse.Log:Error(String, Boolean)
Verse.DefDatabase`1:GetNamed(String, Boolean)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType(Type, Type, String, Object[])
Verse.GenDefDatabase:GetDef(Type, String, Boolean)
RimWorld.DefOfHelper:BindDefsFor(Type)
RimWorld.DefOfHelper:RebindAllDefOfs(Boolean)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

**Comment by abrenneke** [comment]
@Thieffi I had the same error but in my case it was harmless so you should be able to ignore it!

@jptrrs it's caused by the `[DefOf]` trying to load the `HR_Learn` def when it's been removed, even though it's no longer used in Human Resources.

**Comment by jptrrs** [comment]
@abrenneke is right, @Thieffi, totally harmless error. And I just figured that, @abrenneke. I'm removing the removing patch and implementing a line to unload the def at a later stage. Thanks you two!
