### ISSUE TITLE
Androids from Android Tiers can't equip weapons

### ISSUE THREAD

**Issue by TheEventHorizon** [jptrrs/HumanResources#89]
Androids get the "Pawn cannot comprehend this weapon and is scared of it" for all weapons.

**Comment by jptrrs** [comment]
It seems Android Tiers added the "humanlike" marker for the androids, which makes it harder to differentiate them from regular humans. Knowing that, I'm going to lift the barriers for them to get the full Tech Tab and all technology-related functions. This will put them under all conditions imposed to normal pawns as well, making playing with them just as hard as with humans. It might spur other errors somewhere else for them, but it the easiest way to adapt to the mod.

**Comment by TheEventHorizon** [comment]
To be honest that sounds like an optimal solution and will help make androids less OP when using Human Resources so from my perspective its a welcome change! Also worth noting is that the androids from [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1541064015) also had the same issue. And if the Androids from android tiers now function pretty much like normal pawns then I don't see there being any new issues down the road. But if there are I'll be sure to have a detailed bug report posted to the issues tab. It maybe related to a relatively big change in how Humanoid Alien Races handles defs that happened around the 18th of October. Thanks for the quick response!
