### ISSUE TITLE
The Man in Black has no knowledge of his own pistol

### ISSUE THREAD

**Issue by vlad1492** [jptrrs/HumanResources#9]
Guy shows up when a new colony has everyone downed. 
Can't use his six-shooter. 

https://gist.github.com/f345668d0b82d5aefbf3630450187da4

I should have left that donkey alone, but we were so hungry... .

**Comment by jptrrs** [comment]
Ok, that's a good one. I'm on it.

**Comment by jptrrs** [comment]
Fixed for the next update.
