### ISSUE TITLE
"Nowhere to store book" despite having storage

### ISSUE THREAD

**Issue by Maeyanie** [jptrrs/HumanResources#91]
Since this latest update, when I try to right-click force a colonist to write a tech book, it gives me a "Nowhere to store the book when it's finished" message. I have free bookshelf space, tried deleting and re-making the job, and deconstructing and rebuilding a bookshelf. No errors in the log.

![image](https://user-images.githubusercontent.com/206142/97937180-e9f78e80-1d4b-11eb-8125-41ec0139fcb1.png)

**Comment by Maeyanie** [comment]
Restarting the game got it to work again. Could be related to my having bought a number of techs... will update if I see any more patterns.

**Comment by jptrrs** [comment]
Ok, please let me know if you find one.

**Comment by jptrrs** [comment]
If the mod updated in the middle of your game, it could be something with the existing bookshelves. If its still going on, please turn on the dev mode, select a shelf and check on its inspect panel if the "library free space" is correct.

**Comment by Maeyanie** [comment]
Yeah, it did update mid-game. But, I can't reproduce it now, even with buying a number of techs again. May have been a one-time thing on the first load after the update. Either way, since I can't reproduce it, closing this.

**Comment by jptrrs** [comment]
Probably. But Its good to know it can happen anyway. Thanks for the info!
