### ISSUE TITLE
Recreational shooting with CE

### ISSUE THREAD

**Issue by Maeyanie** [jptrrs/HumanResources#92]
With Combat Extended, doing shooting training has always been a bit buggy; when the colonist goes to train, it eats the ammo at 1 shot per frame until it runs out and the person drops the weapon, but it completes the training anyhow so it's never been a huge problem.

However, now that colonists will go shoot for recreation, chewing through a bullet per frame, then reloading, and doing it again, is a bit of an issue.

**Comment by jptrrs** [comment]
This is a known issue with CE, and its not going away soon. If you must use CE, I recommend turning ammo off.

**Comment by Maeyanie** [comment]
Would you be open to a PR with a simple work-around disabling recreational shooting when CE is installed?

**Comment by jptrrs** [comment]
Much appreciated, @Maeyanie . :-) 
But I followed a suggestion from a comment on Steam and implemented a toggle setting for this. Should be up soon, with a quick update. 
What I could really use is a more comprehensive solution to suspend ammo use when training. This has been reported as an issue not only be CE users but other ammo mods as well.

**Comment by Maeyanie** [comment]
Toggle works. 👍 
I'll poke around in the code a bit, see if there's a way to do that without affecting too much... if I find something I'll update this and/or send you a PR.

**Comment by jptrrs** [comment]
That would be great!
You will find the code for the simulation of training at JobDriver_LearnWeapon.Train(Thing currentWeapon). I have no clue on what triggers the ammo spending, but if we find it out I can write a patch to halt it while the pawn is training.

**Comment by jptrrs** [comment]
Other mods that I know of with the same issue:
[Ammunition](https://steamcommunity.com/sharedfiles/filedetails/?id=1892397131) & [Bullet Casings](https://steamcommunity.com/sharedfiles/filedetails/?id=1508411404)
