### ISSUE TITLE
Game startup hangs and never finishes loading

### ISSUE THREAD

**Issue by JinxLuckless** [jptrrs/HumanResources#93]
I have a tribal run modlist that I'm able to start up with just fine, but when I add Human Resources and try to start the game, it gets hung up at a HugsLib stage, and the game never finishes starting up.

My player.log does have an error in it from where it errors out. I'm not sure what it means, but I'm hoping maybe it makes sense to you? I'm hoping not to need to figure out if it's a mod conflict by adding or removing mods a few at a time-- maybe the error indicates it or something.

[Here's a pastebin of my player.log.](https://pastebin.com/Cu9mpLit)

**Comment by jptrrs** [comment]
Hi, Jinx.
The ONLY way to know for sure is by removing or adding mods one at a time and looking for the error. 
But there are a lot of unrelated error messages there. Are you sure its just when you add HR they show up?
Something suspicious is BetterLoading, as it is designed specifically to mess up with the normal loading process.
Something else worth trying is replacing ResearchPal with Research Tree (its outdated but still works) as that's the step which triggers the error.

**Comment by JinxLuckless** [comment]
It's definitely only when I add HR. Weirdly, the error message seems related to Research Tree, now that I've removed ResearchPal.

[Pastebin](https://pastebin.com/i2vLk14P) of the full modlist without ResearchPal, with ResearchTree instead, and minus Better Loading. It loads without a problem.

[Pastebin](https://pastebin.com/H724TbCE) of the same thing, but with HR added, and it just hangs. Because I was testing it, I let it sit for an hour or two just hanging, and then crashed it. When I did, that error was added to player.log.

I plan to play with it more in the next few days, but at least it's a bit more info for now. :)

**Comment by jptrrs** [comment]
Well, it was worth the shot. You can cross Better Loading and ResearchPal from the list of suspects. But notice even without HR there are still a bunch of errors! What I can say from that final error is it happens when HR is trying to process something from the game database. See, the thing with procedurally generating stuff based on other mods is we rely on their contents. If one item is missing (say, from a XML error) or if it is poorly coded, this can cause a hang up. That's what seems to be happening. 
There's no way around it, to find out the conflict you need to reset the mod list to Core, Harmony, HugsLib, ResearchTree/Pal and Human Resources, then add back the other mods one by one.
If it helps, if you send me a list of mods you're using I can tell you what are the ones I know are safe. The HugsLib log includes that list, you only need to start the game without HR and hit Ctrl+F12.

**Comment by chrispikula** [comment]
As a side note, Research Tree (RT) I think defaults to separating the techs by eras.  If HR is forcing RT to make the layout on startup, and you've got a large number of techs, the layout time can increase by orders of magnitude.  As in, it takes me around 30 minutes to start up with RP, of which ~15 are RP & HR.  Making RP sort by tech level in the options balloons this to over 20 hours.

Having an algorithm that checks to see if a tech is out of place, then only fixing a that single tech at a time is bad practice, and another reason that recursive techniques are generally a bad idea.

**Comment by jptrrs** [comment]
That's interesting info, @chrispikula. But no, HR doesn't force an early layout. At most, it forces an early caching. That being said, I know Fluffy optimized the layout generation after ResearchPal forked. That's why I recommend it over RP.

**Comment by JinxLuckless** [comment]
Okay, I think I've figured it out. The only mod that absolutely refuses to load if I put in HR and ResearchTree, is '[Medieval Patches](https://steamcommunity.com/sharedfiles/filedetails/?id=217795847).'

[Relevant player.log](https://pastebin.com/kd0LLZjM)

I wondered if it mattered that Medieval Times wasn't in the short modlist, but that didn't seem to make a difference. It still loaded fine if HR & ResearchTree weren't included.

Strangely, it'll load to the menu (instead of hanging, like other times) if HR is included, as long as ResearchTree isn't also added. The log will have errors saying it can't find ResearchTree, but it still gets to the menu just fine. Even more oddly, just Medieval Patches/HugsLib and ResearchTree (without HR) also loads just fine, so it doesn't seem to be just a ResearchTree issue.

And ResearchPal seems to have the same issue as ResearchTree, where just ResearchPal (and not HR) and Medieval Patches loads up to the menu-- but adding in HR makes it hang again.

[Here's](https://pastebin.com/7z1wpgxT) the log for that. (Medieval Times, Medieval Patches, ResearchPal, and HR all together.)

**Comment by jptrrs** [comment]
That's what I'm talking about!
Now I can start looking into the issue. The only bad side of your pasted log is that unlike the HugsLlib log it doesn't tell me what game and mod versions you're running. I've noticed Medieval Times has not been updated to RW 1.2. Sometimes that's not a problem, but there are a ton of errors in that case, and that might very well be the root of the issue. So I must ask: can you confirm what version of RW, HR and Medieval Times you are using?
BTW, It doesn't crash when loading without ResearchTree/Pal becase HR shuts down in that case.

**Comment by jptrrs** [comment]
Actually, don't bother. I tested it with RW 1.1 and the freeze is still there. But I was able to find what is causing it: one of their patches replaces a tech's pre-requisite with itself, creating an unsolvable paradox for our process, leading to the hang.
I've placed a comment informing the mod author of this and I'm placing a conter-patch on HR while he doesn't fix it.
Thanks for reporting!
