### ISSUE TITLE
Dual Wield Compatibility

### ISSUE THREAD

**Issue by DrZhivago1** [jptrrs/HumanResources#97]
When a pawn does not know how to wield a weapon, they can still equip it in their off-hand.

https://steamcommunity.com/sharedfiles/filedetails/?id=1628211313

**Comment by jptrrs** [comment]
Hi Doc!!
Yes, that will require some patching.... 
Thanks for letting me know.

**Comment by jptrrs** [comment]
Fixed for the next update.
