### ISSUE TITLE
Crahsing after startup

### ISSUE THREAD

**Issue by ghost** [jptrrs/HumanResources#98]
Was building a mod list centered around Human Resources and found that the mod was causing the game not only to crash a few seconds after starting up but seems to completely break the game. After a few seconds on the title screen or mod screen the game crashes. The game does not produce an error log and trying to upload a crash log with CTRL-F12 does not work and then crashes the game.

No Idea what to do and obviously can't supply a log of any sort.

The only mods I'm running are Harmony, Core, Research Pal, and Human Resources (In that order)

I am running Linux in case that can cause this.

**Comment by jptrrs** [comment]
Hi, TizWarp. It seems you are missing [HugsLib](https://steamcommunity.com/workshop/filedetails/?id=818773962), another dependency for Human Resources.
Let me know if that doesn't solve it.
