### ISSUE TITLE
Bizarre training dummy behaviour and Siegers not building mortars/artillery

### ISSUE THREAD

**Issue by account417** [jptrrs/HumanResources#99]
Had a colonist automatically try and use a bolt action rifle to train melee
this caused them to rapidly fire at a colonist
![20201124144643_1](https://user-images.githubusercontent.com/49602644/100088221-b36ee880-2e9f-11eb-9f76-766e053ceff8.jpg)
only a limited amount of damage was done to the colonist however

also no one in a siege knows how to build mortars or vanilla expanded security artillery
maybe make sieges bring uninstalled mortars/artillery instead of materials

**Comment by jptrrs** [comment]
Hi account417, thanks for reporting. But I need more information, please check the procedure explained here:
https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/
About the siege issue, I can say the mod doesn't interfere with non-player pawns actions. In other words, it doesn't matter what they know, the building restrictions only apply to the player pawns.

**Comment by account417** [comment]
I cannot replicate the issue
it potentially could be related to the super training bug however
as the training colonist shot without a cool down which would of given massive amounts of shooting exp
if recreation training exp wasn't disabled

**Comment by jptrrs** [comment]
About the training issue, please refer to issue #90.
